### ISSUE TITLE
Custom validation as a composition of available validations

### ISSUE THREAD

**Issue by Sljux** [mikeerickson/validatorjs#100]
Is there a way to add a custom validation rule as a composition of already present rules? Basically, introducing a shortcut for rules often used together in a project.

Example:

```
'integer|min:1|required' -> 'id'
'numeric|between:-90,90' -> 'latitude'
```

**Comment by iamdtang** [comment]
No there isn't, but that sounds like a great feature if you're interested in adding it.

**Comment by garygreen** [comment]
This doesn't seem much different than doing

``` js
var rules = {
    id: 'integer|min:1|required',
    latitude: 'numeric|between:-90,90'
};

var validator = new Validator({ id: 1, latitude: 0 }, { id: rules.id, latitude: rules.latitude });
```

Where you have a place to specify your common app rules.

**Comment by garygreen** [comment]
Having said that, could add support for passing a string to the `.register()`

``` js
Validator.register('latitude', 'numeric|between:-90,90');
```
