### ISSUE TITLE
Add support for object rules?

### ISSUE THREAD

**Issue by bricejlin** [mikeerickson/validatorjs#102]
Right now, Validator automatically deeply flattens every object, so its impossible to test a value that happens to be an object.

For example, this is the rule I want to validate:

``` js
// input
{
  foo: {
    isTested: false,
    isValid: false,
    isDone: false
  }
}

// rule
{
  foo: 'singleTrueRule'
}

// registered rule
Validator.register('singleTrueRule', value => {
  return Object.keys(value).some(k => k.value === true);
});
```

Any plans to support object rules?

**Comment by LKay** [comment]
How is it different from defining rules for nested object the usual way? The above example shows pretty specific case so I think it's better to have a custom rule defined.

**Comment by bricejlin** [comment]
Right now the `flattenObject` deeply flattens the inputted data, so the above input would be:

```
{
   'foo.isTested': false,
   'foo.isValid': false,
    etc...
}
```

So it would never reach the custom rule I've created, which targets `foo`.

**Comment by LKay** [comment]
That's right, input data shouldn't be flattened apparently. Instead of adding the limit parameter it's better to fix that as it might affect other people's rules. I'll make a fix soon.

**Comment by bricejlin** [comment]
@LKay awesome! thanks for looking into this

**Comment by iamdtang** [comment]
Thanks @LKay !
