### ISSUE TITLE
Missing boolean validation

### ISSUE THREAD

**Issue by glenswift** [mikeerickson/validatorjs#107]
It seems like there's no validation rule for checking if value is boolean out of the box. Or I mess something? Thanks!

**Comment by LKay** [comment]
There is non by default at the moment. I have it locally and can make a PR for it, though.

Currently the library lacks quite a few default rules from the original Laravel validation module.

**Comment by iamdtang** [comment]
if people want to add more of the default Laravel validation rules, PRs are welcome :)

**Comment by glenswift** [comment]
@LKay It would be super awesome. Thanks.

**Comment by iamdtang** [comment]
Thanks! Released in 3.2.0.
