### ISSUE TITLE
custom rules can't depend on another field's value

### ISSUE THREAD

**Issue by farrrr** [mikeerickson/validatorjs#108]
how to validate value depend on another field?

Does custom rule receive all data for validating?

**Comment by garygreen** [comment]
Take a look at the [`same rule`](https://github.com/skaterdav85/validatorjs/blob/master/src/rules.js#L103) you can access the validator and get the input for other fields.

**Comment by farrrr** [comment]
Sorry about that, I found what mistake I made.

I use arrow function so lost "this" reference...

thanks for your help.

**Comment by ravanspell** [comment]
Could you please explain little bit more?
