### ISSUE TITLE
Strict boolean mode

### ISSUE THREAD

**Issue by bezi** [mikeerickson/validatorjs#115]
What do you all think about a strict boolean mode, where only `true` and `false` are accepted?  If not, parsing the looser Boolean mode becomes an issue passed to the implementer, which opens up projects to mistakes based on parsing `'false'` as `true` if devs don't realize that the `boolean` rule is actually quite liberal.

**Comment by iamdtang** [comment]
what if we just followed what Laravel does: https://laravel.com/docs/5.2/validation#rule-boolean

Anything else could be left to a custom rule.
