### ISSUE TITLE
Provide robust date validation.

### ISSUE THREAD

**Issue by klk1010** [mikeerickson/validatorjs#117]
This relies on JavaScript's interpretation of what is considered a date, which is flawed. For example, JS interprets "a-08-02 " as " 8/2/2001. 

It would be nice to have additional functionality built into validatorjs to provide an improvement on this as it is a very common pattern of validation.

**Comment by iamdtang** [comment]
Could you add this and submit a PR? :)

**Comment by klk1010** [comment]
I would love to contribute to this. However, I have my hands full right now with other projects. I solved my issue by using momentjs just for dates. If this is still an issue in a month or two maybe I can try to tackle it when I will (hopefully) have a bit more time.

**Comment by garygreen** [comment]
I think we should do all date validation thru moment.js, it's a very decent library with great documentation. The only trouble is it would add a lot of bulk to validator.js if you don't really need any date validation. We could make it an optional dependency - if you attempted to validate a date and didn't have moment.js it would throw an exception with a friendly message.

**Comment by iamdtang** [comment]
Sounds like a good idea to me. Someone want to implement that?

**Comment by vedmant** [comment]
I also have problems with date validation, it considers "323" as valid date.

**Comment by mikeerickson** [comment]
@skaterdav85 @garygreen  Is this still an open issue?  I ask because the ticket is closed but I don't see any further comment on it (or a PR)

**Comment by mikeerickson** [comment]
@skaterdav85 @garygreen I will attack this one as well today.

**Comment by mikeerickson** [comment]
@garygreen How about we make `moment` a peer dependency and then will check if it is installed, is so it will be used accordingly?

**Comment by garygreen** [comment]
We do now provide basic date functionality. Anything super crazy/complicated should probably be added in userland and use something like moment or other more minimal date libraries.
