### ISSUE TITLE
Custom Validation Doesn't Execute

### ISSUE THREAD

**Issue by bricox** [mikeerickson/validatorjs#118]
I've written a custom validation rule, but have discovered that it doesn't execute if the value that needs to be verified is null or an empty string.  

For example, this does not execute the validation rule.  

Validator.register('telephone', function(val) {  
      return val.match(/^\d{3}-\d{3}-\d{4}$/);
    });

var validator = new Validator({
      phone: ''
    }, {
      phone: 'telephone'
    });

Is this the intended behavior?  It seems to me that this should still run.

**Comment by bricox** [comment]
Ok, so in my research, I've learned that not all rules are implicit rules.  I was thinking about whether we should be able to add to this list for a custom validation.  I'm not sure I actually need it now though.  I was really just trying to implement a required_if rule and now realize there is one. (The documentation needs to be updated.)

**Comment by iamdtang** [comment]
Ya this is the intended behavior. The rule would need to be used in conjunction with the "required" rule.

**Comment by theobroma** [comment]
Example with custom validation telephone rule is incorrect! Replace "match" with "test" instead:

> `   return /^\d{3}-\d{3}-\d{4}$/.test(value);`

**Comment by wbercx** [comment]
In case this helps someone in the future, I ended up registering my rule using `Validator.registerImplicit()`. This seems to work so far.

The workaround of adding `required` to the rules did not work for me, as that was exactly what I was trying to figure out - whether the field is required based on the presence of a value in a supplied array. A `required_if_in` of sorts.

**Comment by Discartyptics** [comment]
@wbercx's solution works perfectly. If a custom rule is essentially a replacement for "require" this is how it must be done.
