### ISSUE TITLE
How to focus on the first invalid field

### ISSUE THREAD

**Issue by shyaaam** [mikeerickson/validatorjs#125]
Is the api method available for this, or a dirty hack ?

**Comment by garygreen** [comment]
There are methods available to access the first error for the given attribute, but if you don't know the attribute you could do something like:

``` javascript
var firstAttribute = Object.keys(validator.errors.all()).shift();
if (firstAttribute) {
   validator.errors.first(firstAttribute); // This is the first error.
}
```
