### ISSUE TITLE
Sync rules should not wait Async ones when using registerAsync()

### ISSUE THREAD

**Issue by foxhound87** [mikeerickson/validatorjs#127]
Using `validation.passes()` after registering an async rule, I get `passes expects a callback when async rules are being tested.`. But I don't need to check all the rules asynchronously.

I don't know if I can do this with the actual version of this package, but I basically I need to get a fails() / passes() of a rule individually, returning a promise.

With a promise I can manage its validation error asynchronously while others rules are running sync.

For example using a code like this for an async `checkUser` rule:

``` javascript
validation.fails('checkUser')
  .then((error) => setError(error));
```

and right after, to set the errors for the remaining sync rules:

``` javascript
if (validation.fails()) {
  setError(validation.errors.get());
}
```

I hope this suggestion will help,
Thank you for the this cool library!

**Comment by garygreen** [comment]
It wouldn't make much sense to not check all the rules, and if any one of them is async then you need to pass a promise otherwise it can't give you the final result of all of them, that's why you get that error message. All the rules are processed one by one, if you want to stop on the first error (which could be an async one) just use `stopOnError` function. To me it sounds like you need two validators though.

**Comment by foxhound87** [comment]
I don't think `stopOnError` could help in my case.

I want to show the sync errors first, and then show the async one only when is resolved.
(And I need to know if it's an async error or not).

Probably two validators (one async and one sync) can be the way.

**Comment by garygreen** [comment]
Can't you put your sync rules first, then async rules then use `validator.stopOnError(true)` ? That would show the sync errors as soon as there is one, and not process the async rule.. then if all sync rules pass it would go onto async rule.

**Comment by foxhound87** [comment]
I'm using your lib to develop validation for a reactive form lib, and the behavior should be transparent to the user. He should not care about the sequence of the rules. That's a big deal?

**Comment by garygreen** [comment]
Well you could detect what rules are sync / async and re-order them.

**Comment by garygreen** [comment]
Closing as `stopOnError` or two validators is your best bet.

**Comment by foxhound87** [comment]
`stopOnError` didn't help in my case as I'm performing validation for each field separately.
Maybe `hasAsync` would help me but it's not documented and I didn't noticed it, so I ended up splitting the rules.

About the passes() and fails() methods, would be cool to use it with a `promise` style instead the regular `callback` style. 

Thank you for your support.
