### ISSUE TITLE
should throw an exception if rule is missing

### ISSUE THREAD

**Issue by demsey2** [mikeerickson/validatorjs#128]
in validator.js "check" method should throw an exception. I just spent a bit debugging why my validation doesn't work on node server. I use same data on client and server but forgot to register custom validation rule and node didn't respond at all

```
    rule = this.getRule(ruleOptions.name);
    if (!this._isValidatable(rule, inputValue)) {
      continue;
    }

    rulePassed = rule.validate(inputValue, ruleOptions.value, attribute);
```

isValidatable only checks for implicite rules then validation is called but no results if custom rule is not registered

**Comment by iamdtang** [comment]
on vacation for another week. @garygreen can you look at this?

**Comment by garygreen** [comment]
@demsey2 this has caught me out a few times as well, it would be a nice feature to have it check and throw an exception if rule doesn't exist. Care to do a PR? :)

**Comment by mauvm** [comment]
I've had the same problem:

```js
TypeError: Cannot read property 'apply' of undefined
    at Object.Rule.validate (./node_modules/validatorjs/src/rules.js:324:19)
```

Turned out it accidentally used `number` instead of `numeric`.

**Comment by afitiskin** [comment]
It would be nice to add possibility to set custom validator for ALL missing rules
