### ISSUE TITLE
custom messages per field

### ISSUE THREAD

**Issue by demsey2** [mikeerickson/validatorjs#130]
at the moment when a new instance of validator is created we can pass custom messages object,
what if I want to have a custom message for "numeric" type but only for a certain field, at the moment custom message will be applied to all fields with a that type

**Comment by garygreen** [comment]
You should be able to supply per-attribute custom messages in the format `<rule>.<attribute>` like this:

``` js
var validator = new Validator({ num1: 1, num2: 2 }, { num1: 'min:5', num2: 'min:5' }, { 'min.num1': 'Not big enough bro' });
if (validator.fails()) {
    console.log(validator.errors);
}
```

It's not mentioned in the docs, should probably be added.

**Comment by demsey2** [comment]
thanks @garygreen that works as expected, it would be good to updates docs so we can avoid more issues like this

**Comment by stemsmit** [comment]
This does now appear to be documented in the last code block of the [Custom Error Messages](https://github.com/skaterdav85/validatorjs#custom-error-messages) section. So this can probably be closed.
