### ISSUE TITLE
Add `present` rule

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [mikeerickson/validatorjs#133]
It would be great to have a rule which makes sure that a field is present in the input data. Require doesn't always cut it if you also want to allow empty input values.

It should also make sure that all the sibling rules will validate so that its possible to validate empty values.

``` javascript
// Should pass
new Validator({
  name: ''
}, {
  name: 'string|present'
);
```

``` javascript
// Should fail
new Validator({}, {
  name: 'string|present'
);

// Should fail
new Validator({
  name: []
}, {
  name: 'string|present'
);
```

**Comment by iamdtang** [comment]
so this? https://laravel.com/docs/5.4/validation#rule-present

**Comment by mikeerickson** [comment]
@Patrik-Lundqvist @skaterdav85 I will work on getting this added in the next day or so.  Have used this rule numerous times within Laravel, so I can appreciate the need for it here :-)

**Comment by iamdtang** [comment]
Thanks @mikeerickson !

**Comment by mikeerickson** [comment]
@skaterdav85 I have completed #158 (PR created) and will now move onto this item.

**Comment by mikeerickson** [comment]
@skaterdav85 @garygreen I have this feature implemented, but I have only created the english error message.  How do you go about translating to other languages (did you use google translate) or do you have translation resources.

**Comment by mikeerickson** [comment]
I have the following completed

- [x] de
- [ ] el
- [x] en
- [x] es
- [ ] fa
- [x] fr
- [x] it
- [ ] ja
- [ ] nb_NO
- [x] pl
- [ ] pt
- [ ] ru
- [ ] tr
- [ ] vi
- [ ] zh_TW
- [ ] zh

If any of you are seeing this and can assist with language translation, I would be appreciative.  Here is the english version

```
The :attribute field must be present (but can be empty).
```

**Comment by mikeerickson** [comment]
@Patrik-Lundqvist @skaterdav85 @garygreen The applied syntax for `present` is 

The following rule is `present` passes validation

```
...
var validation = new Validator({
  email: ''
}, {
  email: 'present'
});
...

```

The following rule is `present` fails validation

```
...
var validation = new Validator({
  fname: 'Mike'
}, {
  email: 'present'
});
...

```

**Comment by iamdtang** [comment]
@mikeerickson 2 options, either go to Google Translate or just put in the english version and when someone who comes across this sees the error not in their language, then they can make a PR and update it.

**Comment by mikeerickson** [comment]
@skaterdave85 ok, I will post PR with the translations I do have.
