### ISSUE TITLE
Custom attribute replacements for custom rules

### ISSUE THREAD

**Issue by jelteliekens** [mikeerickson/validatorjs#136]
It would be nice to have custom replacements for a custom rule using the `Validator.register()` function.

Ex.:

``` javascript
Validator.register(
    'dateBetween',  
    function (value, requirement) {
        // custom validation using dates
    },
    function (parameters) {
        return {
            min: parameters[0],
            max: parameters[1],
        });
    },
    'Custom message for attribute :attribute with replacements :min and :max.',
);
```

**Comment by dmackerman** [comment]
This would be really nice.

**Comment by vedmant** [comment]
Yeah, I'm searching right now how I can replace placeholder with passed parameter in custom rule error message, and it looks like I just can't :( At least it could allow to generate error message inside custom rule function.

**Comment by mikeerickson** [comment]
Sounds like a good idea.  I will work to get this added in next version (along with many other updates)

**Comment by mingjinc** [comment]
@mikeerickson Thanks, Any plan to add it in the release?

**Comment by mikeerickson** [comment]
Yes, most definitely :)

**Comment by dehypnosis** [comment]
Any progress?

**Comment by vedmant** [comment]
Any updates here?

**Comment by rennerDa** [comment]
https://github.com/anwr-group/validatorjs/blob/master/spec/register.js
In this fork you can add custom replacements.

**Comment by felipe-gustavo** [comment]
I know this is so old, but I recently add a pull request( #375 ) with the proposed changes to this to works.

**Comment by mikeerickson** [comment]
This feature was added in `v3.19`
