### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by jackvial** [mikeerickson/validatorjs#137]
Typescript support would be nice 😄

**Comment by prawana-perera** [comment]
Yes I agree 1+

**Comment by iamdtang** [comment]
Maybe in the future. I think I'd like to move to ES6 first. Once enough people are familiar with TS, then we can consider adding it to this library.

**Comment by harrygr** [comment]
It seems the [typings are available](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/validatorjs) as part of the DefinitelyTyped project so you should be able to install them with `yarn add @types/validatorjs` (although I have yet to try).

It would be nice to have some officially supported typings in the project though.
