### ISSUE TITLE
Before assigning to validatorjs we need to convert first all object value to string

### ISSUE THREAD

**Issue by apmeena** [mikeerickson/validatorjs#142]
@skaterdav85 i have a JavaScript object 

```
var data  = {
   name:"John",
   emp_id:1223
} 
```
if i want to put some validation on `emp_id` field then first i need to convert it to string like "1223" or '1223', if i don't convert it generates error. Is there any configuration setting or it is mandatory or i am doing some mistake?

**Comment by garygreen** [comment]
The type of value is pretty important in how validatorjs knows how to validate a value. It's not clear what sort of rules your trying to validate, closing for now.
