### ISSUE TITLE
Automatic creation of Javascript validation based on Laravel FormRequests

### ISSUE THREAD

**Issue by antonkomarev** [mikeerickson/validatorjs#147]
Is there any plans to implement conversion from Laravel's form request classes to javascript equivalent on the fly? Maybe not in exactly this package...

Something like:
```php
{!! ValidatorJs::formRequest('App\Http\Requests\ArticleFormRequest') !!}
```

**Comment by mikeerickson** [comment]
@a-komarev @skaterdav85 I have thought about doing this very thing.   

David, If you want me to add this, please let me know

**Comment by iamdtang** [comment]
Could you provide more details on this (i.e. the various uses cases and how it would work)?

**Comment by garygreen** [comment]
This would be pretty cool but I think it would be best as an optional library. I'm not sure it's something we would want to maintain internally. Also it could be quite tricky to implement a lot of flexibility in how you can create validation rules in Laravel and have them converted to validatorjs equivalent. But if you find a way and release it as a package, let us know and we can update the readme and link to it 👍
