### ISSUE TITLE
Validator is not available during Angular testing 

### ISSUE THREAD

**Issue by apmeena** [mikeerickson/validatorjs#151]
@skaterdav85, I am using validatorjs with Angular js, The application is working fine as expected, but during testing `Validator ` is not defined error I am facing. Because in Angular js we need to inject each and every plugin or library we are using in our module and controller. But we are not injecting here we are directly using:

`var validation = new Validator(data, rules [, customErrorMessages]);`

So inside all the controllers it is available globally, but how can I access it as a service or a factory?

**Comment by iamdtang** [comment]
Access it globally in the service or factory.

**Comment by apmeena** [comment]
But we don't have access in testing. What can I do for it?

**Comment by iamdtang** [comment]
Is it getting loaded in your test harness?
