### ISSUE TITLE
Empty Array passes validation using "between" rule.

### ISSUE THREAD

**Issue by foxhound87** [mikeerickson/validatorjs#152]
Using `array|between:3,5` with an **empty array** the validation passes. But it shouldn't.

I think if I specify the required minimum number of elements greater than zero, providing an empty array, it should throw error.

Furthermore I think the `required` rule should be used to check if the array is present (not undefined/null).

I was discussing an issue [here](https://github.com/foxhound87/mobx-react-form/issues/173) and it seems we misunderstood the use of the rules, but we both expected they worked as I explained.

Thank You.

**Comment by iamdtang** [comment]
How does Laravel handle this? I say we should keep in line with Laravel's behavior. If it isn't in line, could you submit a fix? :)

**Comment by mikeerickson** [comment]
@foxhound87 @skaterdav85 If he does not want to (or have time to) submit a PR, I will take care of it.

**Comment by garygreen** [comment]
Duplicate of #131
