### ISSUE TITLE
Async validation run twice

### ISSUE THREAD

**Issue by foxhound87** [mikeerickson/validatorjs#155]
I call both .passes() and .fails()  to check the async validation. 
Right now I don't find any solution to check both validation states without calling both of them.
This runs the validation twice.

I think we need a method which runs the async function only one time and calls respectively passes/fails callbacks. Or at least a promise implementation (as I proposed in this issue: https://github.com/skaterdav85/validatorjs/issues/127)

For example a possible solution could be to provide a validation function which accept an object with the two callbacks:

```javascript
validator.validate({
  passes: () => {},
  fails: () => {},
});
```

We discussed the problem in this issue:  https://github.com/foxhound87/mobx-react-form/issues/214

Thank You.

**Comment by garygreen** [comment]
What about [`checkAsync`](https://github.com/skaterdav85/validatorjs/blob/master/src/validator.js#L86) ?

**Comment by foxhound87** [comment]
Is it already available? I don't see it documented

**Comment by foxhound87** [comment]
That's working.
Thank You.

**Comment by raghavgarg1257** [comment]
@foxhound87, Please can you share how did you overcome this problem using `checkAsync`. Any type of help is appreciated.

**Comment by foxhound87** [comment]
@raghavgarg1257 take a look at this commit: 

https://github.com/foxhound87/mobx-react-form/commit/b74be11f3d16af53870a55a9e5a26654dbff4b36

**Comment by raghavgarg1257** [comment]
@foxhound87 Thanks, for the reply.

**Comment by alisherafat01** [comment]
@foxhound87 
Can you write a real example here? 
I have this issue and can't figure out how to resolve.
