### ISSUE TITLE
confirmed

### ISSUE THREAD

**Issue by peshi** [mikeerickson/validatorjs#156]
Hi!, I am using synchronous validation and I am getting an error in my form before any input in the confirmation field. Shouldn't the 'confirmed' rule actually display an error on the _confirmation field?

To demonstrate a simple set of rules.

Example:
```
import Validator from 'validatorjs';
import _ from 'lodash';

const rules = {
  username: 'required',
  password: 'required|confirmed',
  password_confirmation: 'required,
};

export const validate = (values) => {
  const validator = new Validator(values, rules);
  validator.passes(() => {});
  return _.mapValues(validator.errors.all(), (value) => _.toString(value));
};
```

Actual result:

Username
Password [**error**]
Confirm password
```
      syncErrors: {
        password: 'The password confirmation does not match.'
      }
```

Desired result:

Username
Password
Confirm password [**error**]
```
      syncErrors: {
        password_confirmation: 'The password confirmation does not match.'
      }
```

**Comment by peshi** [comment]
It seems that I also could use ```same:password``` on *_confirmation fields or some custom sauce.

Closing.

**Comment by ebenezermakinde** [comment]
This is a great read. I actually had the same issue. This PR actually help me out. Thanks @peshi
