### ISSUE TITLE
.get method is not returning array, only first item

### ISSUE THREAD

**Issue by mikeerickson** [mikeerickson/validatorjs#158]
Using the example from docs, the last line `validation.errors.get` only returns the first item (and the array length is 1)

```
var validation = new Validator({
  name: 'D',
  email: 'not an email address.com'
}, {
  name: 'size:3',
  email: 'required|email'
});

// Error messages
let result;
result = validation.errors.first('email');
console.log(result); <-- returns first failure message
result = validation.errors.get('email'); 
console.log(result.length); <-- returns a single element (matching above)
```

**Comment by mikeerickson** [comment]
I pasted the wrong, example

```
var validation = new Validator({
  name: 'D',
  email: ''
}, {
  name: 'size:3',
  email: 'required|email|min:3'
});

validation.fails(); // true

// Error messages
let result;
result = validation.errors.first('email'); // 'The email format is invalid.'
console.log(result);
result = validation.errors.get('email'); <-- only returns first error, not list
console.log(result.length);
```

**Comment by iamdtang** [comment]
Yes, get returns a list of errors and first returns the first. See the tests: https://github.com/skaterdav85/validatorjs/blob/master/spec/error-messages.js

**Comment by mikeerickson** [comment]
@skaterdav85 Hey David, please humor me on this one :-)

This test is the crux of this issue.   Based on my interpretation, shouldnt this return failed validations

1. for missing `email`
2. for invalid `email`

I am expecting that 2 items would be returned for the last validation

```
expect(validator.errors.get('email').length).to.equal(1);
```

I am referring to this test from what you sent me

```
  describe('get()', function() {
    it('should return an array of all email error messages', function() {
      var validator = new Validator({
        email: ''
      }, {
        email: 'required|email'
      });

      expect(validator.passes()).to.be.false;
      expect(validator.errors.get('email')).to.be.instanceOf(Array);
      expect(validator.errors.get('email').length).to.equal(1);
    });
```

**Comment by iamdtang** [comment]
You're right. This looks like a bug. Want to fix? :)

**Comment by mikeerickson** [comment]
@skaterdav85 Sure thing!  :-)

Glad I wasn't losing my mind!  I am on it now

**Comment by garygreen** [comment]
Doesn't this have to do with the implicit rule? If the required rule doesn't pass then it shouldn't continue validating the rest... this could be a breaking change for most if it did. This works as expected imo.

**Comment by iamdtang** [comment]
Ah, ok. Then we should document that. Could you do that @garygreen?

**Comment by mikeerickson** [comment]
@garygreen this issue occurs regardless of required. If I have a rule such as `email|min:3` it will return one result.  Further, it is no specific to email, that is just an example.  In short it always stop at the first item.

**Comment by garygreen** [comment]
Your right `email|min:3` should be returning multiple, it looks like we don't have any tests for multiple messages... strange. `required|email|min:3` wouldn't return multiple if the implicit rule failed, though.

**Comment by mikeerickson** [comment]
@garygreen and this my friend is why I opened this issue :). I am going to be tackling fixing this issue today as it is important for my usage (unless you have a reason I should not)

**Comment by iamdtang** [comment]
Thanks @mikeerickson!
