### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mikeerickson** [mikeerickson/validatorjs#159]
I am wondering if this project is actually still maintained?  It seems that activity from contribs has vanished and many issues (and PRs) seem to be quite stale and outdated.

**Comment by iamdtang** [comment]
I responded to your email.

**Comment by ozziest** [comment]
Hello @mikeerickson, @iamdtang.  

Thank you very much for your efforts on this project. I really love to use it. ❤️ 👏 🙇 
I just want to ask the same question after five years; 

  **_"Is this project still maintained?"_**
