### ISSUE TITLE
How use stopOnError

### ISSUE THREAD

**Issue by calmeyda** [mikeerickson/validatorjs#160]
Hi, I guess this is the best validator for nodejs, but I'm having the next issue (non critic but would be great for performance care)

I can't find an example about how use stopOnError, I see on souce code it receive a boolean (true for all fields) or array, I tried set it true on main instance (as config language) and on instance of it but the validation always fired my custom async validation.
My rule:
`{name    : `required|max:20|unique:measure_units,name,${id}`,}`
If I send a name with 21 characters it fires the unique rule, if I don't send name value if don't fires nither max nor unique

I'm using the last validatorjs version over nodejs 6.9.4

Thanks for your help

**Comment by iamdtang** [comment]
@garygreen do you know how this feature is used? I think you added it :)

**Comment by garygreen** [comment]
stopOnError doesn't actually support async at the moment, unfortunately haven't had time to look into adding that feature yet, which is partly why I haven't documented it yet. https://github.com/skaterdav85/validatorjs/blob/master/spec/stop-on-error.js#L21.

**Comment by santosjs** [comment]
@garygreen Does this feature appear in the near future? Faced with this problem. Would be great to have some sort of stopOnError function
