### ISSUE TITLE
Async validators called twice, first for fails and then again for passes callback

### ISSUE THREAD

**Issue by mogarick** [mikeerickson/validatorjs#168]
When there are only sync validators I can check if it passes or fails using only either a call to `validation.fails()` or `validation.passes()` like so:

``` javascript
let validation = new Validator(data,rules);
if (validation.passes()) {
        //handle passed validation        
      } else {
        //handle failed validation
      }
```
In this scenario the validation test runs only once, when calling to `fails()`.

The problem arises when Async Validators are present. It needs to be a `callback` when calling `fails` or `passes` functions but in order I can cover both fail and pass scenarios I'd need to call both functions, like so:

``` javascript
let validation = new Validator(data,rulesWithAsyncValidators);
validation.passes(()=>{
  //handle passed validation
});
validation.fails(()=>{
  //handle failed validation
});
```
In this async scenario the validation test runs twice, first when calling `passes` and then again when calling `fails`.

Looking into de source code I see that both functions call `checkAsync` which accepts bot `passes` and `fails` functions but depending on which one called it (`fails` or `passes`) only one is real and the other is empty.

So I think a new function that allows both `fails` and `pases` callbacks would be very useful and it would avoid the duplicated validation mentioned in the async scenario.

I modified locally the source to include the next method in `validator.js` (the name is my personal suggestion):

``` javascript
/**
   * Determine if validation either passes or fails
   * @param {function} passes
   * @param {function} fails
   * @return {boolean|undefined}
   */
  test: function(passes,fails) {
    var isPassesAsync = this._checkAsync('passes', passes);
    var isFailsAsync = this._checkAsync('fails', fails);
    if(isPassesAsync && isFailsAsync) {
      return this.checkAsync(passes,fails);
    }
    return this.check();
  }
```

with this method you call it with 2 cb functions, one for each case, and this way the double validation doesn't occur anymore. Example code:

``` javascript
let validation = new Validator(data,rulesWithAsyncValidators);
validation.test(
        () => {
         //handle passed validation
        },
        () => {
          //handle failed validation
        }
      );
```

What you think? would you add this new method or may I send a PR?

Thank you in advance for your attention and congratulations for such awesome lib!

**Comment by garygreen** [comment]
Maybe I'm misunderstanding what your asking but what's wrong with just calling `checkAsync(passes, fails)` with the appropriate callbacks?

**Comment by mogarick** [comment]
@garygreen it could be an alternative, but I didn't consider it appropriate at all because:
1. It was not documented in the `readme.md` document. 
2. Calling it directly doesn't have the benefit of calling the private method `_checkAsync` for verification of the cb to be properly functions. In this respect I either avoid to honor the code convention suggestion of `_checkAsync` being private and calling it from outside before calling `checkAsync`, or duplicate the `_checkAsync` logic in a external method (no big deal because is so small but I think if it's already there it wouldn't be the best approach to repeat it outside).

That's why my personal and local solution was to add a method directly in the `validationjs` prototype that exposes the `checkAsync` functionality of being able to have both `passes` and `fails` cb and reusing the `_checkAsync` without breaking the convention of calling `_private` methods from outside.

Did I explain myself better? :)

**Comment by garygreen** [comment]
Meh. I think this just overcomplicates the library adding yet another way to validate data. There is no real benefit to type checking the `checkAsync` method as it's name inherently implies that promises need to be supplied.

**Comment by vedmant** [comment]
This should be in the documentation, I was having problems with opposite, when only one method was called either passed() or fails() the one that goes first.

**Comment by mikeerickson** [comment]
For those who have stumbled upon this ticket, the above discussion about not being in the documentation is no longer the case (as of v3.13) and can be found under the "Asynchronous Validation" section

**Comment by altaf53** [comment]
I am facing same issue. Is there any solution yet?
