### ISSUE TITLE
before:date, after:date are missing?

### ISSUE THREAD

**Issue by vedmant** [mikeerickson/validatorjs#170]
It looks like rules `before` and `after` are missing, they have been available in Laravel even in 4.x.

**Comment by mikeerickson** [comment]
@vedmant they will be in next update.  Working on them tomorrow.

**Comment by prasadedlabadkar** [comment]
Do you know any tentative date for this update?

**Comment by mikeerickson** [comment]
@prasadedlabadkar My apologies for delay, I will aim to wrap these up by tomorrow (2017.04.12)

**Comment by mikeerickson** [comment]
@prasadedlabadkar This has been cured and included in the 3.12.0 release which was recently published.
