### ISSUE TITLE
Stricter validation for URLs

### ISSUE THREAD

**Issue by tsriram** [mikeerickson/validatorjs#182]
This lib currently checks only if the given string contains `http://` or `https://` followed by at least one character. So invalid URLs like `http://a` and `https://google` pass the validation. I think we can use a better regex to validate URLs. One regex which I found to be doing a comprehensive validation is here - https://github.com/poppinss/indicative/blob/bd90485ad4cea1fa334f2a7f1e7019cf3345507c/src/Raw/index.js#L17

If this looks good, I can send in a PR with relevant tests.

PS - Of course, users can pass the regex directly instead of `url`, but it'd be great if the lib does it out of the box.

**Comment by iamdtang** [comment]
Sounds good! Thanks!
