### ISSUE TITLE
How to access data inside of custom validation

### ISSUE THREAD

**Issue by alanhr** [mikeerickson/validatorjs#188]
Hi, 
I need access the value of other field inside of the data equal a **[required_if](https://github.com/skaterdav85/validatorjs/blob/master/src/rules.js#L47),** but in callback I don't have access this values.

Why not pass the **input** as the last param ?

**Comment by raiman264** [comment]
I noticed that you have access to `input` in the `this` object
for example:
```
validatorjs.register(
  'equals',
  function equalsRule(value, requirement) {
    return value === this.validator.input[requirement];
  },
   'The :attribute must be equals to :requirement.'
);
```
where requirement is a field name

**Comment by smithaitufe** [comment]
Hi @raiman264 Please how did you access the name of the second field? The `:attribute` property works but the` :requirement` does not

**Comment by ravanspell** [comment]
> I noticed that you have access to `input` in the `this` object
> for example:
> 
> ```
> validatorjs.register(
>   'equals',
>   function equalsRule(value, requirement) {
>     return value === this.validator.input[requirement];
>   },
>    'The :attribute must be equals to :requirement.'
> );
> ```
> 
> where requirement is a field name

What if we don't have access to "this" instance?

**Comment by ravanspell** [comment]
> Hi @raiman264 Please how did you access the name of the second field? The `:attribute` property works but the` :requirement` does not

In your case it's easy
validation: 'min:3|formula-format: 3'

add your field name as the second param. for instance, above assume `formula-format` is a custom validation rule.
you can insert the field name you intend to access as '3' in the above example. then you will get  "requirement" = 3  in this case.
