### ISSUE TITLE
3.13.0 release

### ISSUE THREAD

**Issue by afitiskin** [mikeerickson/validatorjs#199]
Last release 3.12.0 was few months ago, we have few very interesting features merged in master, but its not available on npm. @mikeerickson and @skaterdav85 please make new release.

**Comment by mikeerickson** [comment]
@afitiskin  I am working on getting this done asap.  I have been swamped at work.

**Comment by hassankhan** [comment]
Please do consider adding a trusted contributor and/or a CI process that releases `master` to NPM automatically. Definitely helps with the workload 👍

**Comment by afitiskin** [comment]
@mikeerickson I see version 3.13.3 at npm, but it not contains latest features. Can we update the package on NPM?

**Comment by mikeerickson** [comment]
@afitiskin I will be producing 3.14 this weekend (Saturday) and would recommend waiting until that version is available.

**Comment by aserhii87** [comment]
+1 
We waiting new release, because in my project when i use v3.12.0 i have a trouble with date validation

**Comment by iamdtang** [comment]
I just released 3.13.4. Closing for now. Let me know if this needs to be reopened.
