### ISSUE TITLE
Is NPM version the latest one?

### ISSUE THREAD

**Issue by limboooow** [mikeerickson/validatorjs#204]
Find wildcard function missing in NPM version.

**Comment by mikeerickson** [comment]
No, there are some versioning issues I am working out. Should be cleared up tomorrow.

**Comment by JonathanGuo** [comment]
https://yarnpkg.com/en/package/validatorjs

There is no validator.min.js under dist folder in yarnpkg

**Comment by mikeerickson** [comment]
@JonathanGuo Not quite done, hope to get this wrapped this afternoon.

**Comment by vladshcherbin** [comment]
@mikeerickson can you publish new version?

Docs are [misleading](https://github.com/skaterdav85/validatorjs/issues/205)

**Comment by iamdtang** [comment]
I just published 3.13.4. Is this still an issue?

**Comment by vladshcherbin** [comment]
@shabushabu thanks, this is working in 3.13.4, probably can be closed.

**Comment by JonathanGuo** [comment]
`3.13.4`'s files are still not quite right on yarn.

https://yarnpkg.com/en/package/validatorjs


When I browse the file I got the error:
```
Could not load file listing: Unexpected token < in JSON at position 0
```

In the repo I installed, the `validator.min.js` doesn't exist. But I can get `validator.js`, this is fine.

**Comment by iamdtang** [comment]
Ah, validator.min.js was removed not too long ago. Use validator.js. I updated the docs and published a new version (3.13.5). I'm not sure when the yarn docs get updated, so look at the docs on Github or NPM. Does that resolve this issue?

**Comment by JonathanGuo** [comment]
Yep. To me I only need to update my gulpfile. :)
I think it's all good as long as it's documented.

**Comment by iamdtang** [comment]
awesome!
