### ISSUE TITLE
npm is not pulling the latest validator package

### ISSUE THREAD

**Issue by harry46nv** [mikeerickson/validatorjs#208]
I see in the -v@3.13.3-----> rules---> have been updated so that there wont be any issue with date on line@18.
But the package npm is pulling when I try to install the latest v of validatorjs still have 
var mo = testDate.getMonth() + 1;----> which might be some older version,
which is resulting in unexpected results.

How could I resolve this issue.?

**Comment by mikeerickson** [comment]
@harry46nv the latest version of validatorjs is now available with npm

```
$ npm install -S validatorjs
```
