### ISSUE TITLE
Dynamic require() breaks RN 49.0+

### ISSUE THREAD

**Issue by agrosner** [mikeerickson/validatorjs#214]
<img width="337" alt="screen shot 2017-10-05 at 4 31 47 pm" src="https://user-images.githubusercontent.com/2117859/31251045-b527dd90-a9ea-11e7-9358-3655d781de7b.png">

This error appears when trying to run our app with react native 0.49. It appears to be breaking a few other libraries including realm and moment.js (https://github.com/facebook/react-native/issues/16216)

**Comment by konradkierus** [comment]
Yep, but I can confirm that fixing this in realm way https://github.com/realm/realm-js/commit/e1b70c2f573e51dfbd6b8b42e3c8d8851744bb6c does fix the issue but... there is a debate going on here https://github.com/facebook/metro-bundler/issues/52 (packager for React Native) if this shouldn't be fixed on packager itself.
Anyway, realm workaround wouldn't harm here.

**Comment by danieloprado** [comment]
@konradkierus make a pull request

**Comment by konradkierus** [comment]
@danieloprado I didn't want to do this as there is still a debate on metro-bundler if it shouldn't have an option to allow dynamic imports https://github.com/facebook/metro-bundler/issues/65
But! The workaround doesn't break anything so it could be merged if project's author is ok with this.
