### ISSUE TITLE
after:date Invalid date format

### ISSUE THREAD

**Issue by loyd-cpi** [mikeerickson/validatorjs#217]
Validatorjs returning an error saying that I have an invalidate date format, but this only happens on specific dates. When I change the `end_date` to let say `01/28/2018` it works, but when I get up to `29-31` its returning Invalidate date format for `end_date`.

```
let start_date = '01/01/2018';
let end_date = '01/31/2018';
let rules = { 
  start_date: 'required|date',
  end_date: 'required|date|after:start_date',
};
```

Thanks. Love your work by the way.

**Comment by iamdtang** [comment]
I don't have much time to look into this. Would love it if you could send a PR :). This would be the file: https://github.com/skaterdav85/validatorjs/blob/master/src/rules.js

**Comment by mikeerickson** [comment]
Hey gang, I will have a look at this tomorrow.  I have addressed issues similar to this in the past and should be a pretty straightforward fix
