### ISSUE TITLE
Unkown named module:'./lang/en'

### ISSUE THREAD

**Issue by apatche7** [mikeerickson/validatorjs#221]
I got this message  `Unkown named module:'./lang/en'` when I'm trying to use the package 
and the package already exists in `node_modules` i tried to remove `node_modules` and install it again but nothing work and tried to clean the cache also but nothing work out..!!

That's my code 

`import React, {Component} from 'react';
import { Actions } from 'react-native-router-flux';
import Icon from 'react-native-vector-icons/FontAwesome';
import * as Animatable from 'react-native-animatable';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import { reduxForm, Field } from 'redux-form';
import { connect } from 'react-redux';
import FCM, { FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType, Item, Input } from 'react-native-fcm';
import * as actions from '../actions';
var Validator = require('validatorjs');
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    Image,
    TextInput,
    Button,
    TouchableHighlight,
    TouchableOpacity,
    ImageBackground,
    ScrollView
    
} from 'react-native';

import styles from '../styles'
import bg from '../img/background.png'
import logo from '../img/logo.png'
import rdTextInput from '../containers/rdTextInput'

class HomeScreen extends Component {

    componentDidMount() {
        FCM.getFCMToken().then(token => {
            this.props.setDeviceToken(token);
        });
    }

    phoneChnage(text) {
        this.props.phoneChnaged(text);
    }

    onLogin = () => {
        const rules = {
            name: 'required|min:2',
            email: 'required|email',
            age: 'numeric|min:18',
        };
        const { name, email, age } = this.props;
        const data = { name, email, age };
        const validation = new Validator(data, rules);
        validation.fails(() => {
            console.log('validation.errors.all()', validation.errors.all());
            this.setState({ errors: validation.errors.all() });
        });
        console.log('onLogin');
        // Actions.main();
    }
    // signUp
    onSingUp = () => {
        console.log('SignIp')
        Actions.SignUp()
    }
    // forgetPassword
    onforgetPassword = () => {
        console.log('forgetPassword')
        Actions.ForgetPassword()
    };

    render() {
        const { handleSubmit, reset } = this.props; 
        return (
            <ScrollView style={{padding: 0}} keyboardDismissMode='none' pagingEnabled={true}>
                <KeyboardAwareScrollView enableAutoAutomaticScroll={false}  resetScrollToCoords={{ x: 0, y: 0 }} scrollEnabled={false} enableOnAndroid={true}>

                    <ImageBackground source={bg} style={[styles.bg, styles.scrollContainer, {paddingVertical: 100}]}>

                        {/* Logo */}
                        <View style={styles.header}>
                        <Animatable.Image animation="fadeInDown" source={logo} style={styles.logo}></Animatable.Image>
                        </View>
                        
                        <View style={styles.footer}>
                            {/* Input */}
                            <View style={styles.inputsContainer}>
                                <View style={styles.labelContainer}>
                                    <Text style={styles.label}> رقم الهاتف </Text>
                                    <Icon name="mobile" style={[styles.icon]}/>
                                </View>
                            <TextInput style={styles.input}
                                    onChangeText={this.phoneChnage.bind(this)}
                                    vaule={this.props.phone}
                            ></TextInput>

                            <Field
                                name={'email1'}
                                component={rdTextInput}
                            />

                            <TouchableOpacity onSubmit={handleSubmit}>
                                <Text>Submit!</Text>
                            </TouchableOpacity>
                            </View>

                            {/* Input */}
                            <View style={styles.inputsContainer}>
                                <View style={styles.labelContainer}>
                                    <Text style={styles.label}> كلمة المرور </Text>
                                    <Icon name="lock" style={[styles.icon]}/>
                                </View>
                                <TextInput secureTextEntry={true} style={styles.input}></TextInput>
                            </View>

                        {/* loginFooter */}
                        <View style={styles.loginFooter}>

                            <View style={styles.loginFooterLinks}>

                                {/* onforgetPassword */}
                                <TouchableOpacity onPress={() => this.onforgetPassword()}>
                                    <Animatable.Text
                                        animation="fadeIn"
                                        delay={700}
                                        style={styles.loginFooterLinksText}>نسيت كلمة المرور؟</Animatable.Text>
                                </TouchableOpacity>

                                {/* onSingUp */}
                                <TouchableOpacity onPress={this.onSingUp}>
                                    <Animatable.Text
                                        animation="fadeIn"
                                        delay={900}
                                        style={styles.loginFooterLinksText}>ليس لديك حساب؟</Animatable.Text>
                                </TouchableOpacity>

                            </View>

                            {/* onLogin */}
                            <TouchableOpacity onPress={() => this.onLogin()}>
                                <Animatable.Text animation="fadeInUp" delay={600} style={styles.button}>
                                    دخول
                                </Animatable.Text>
                            </TouchableOpacity>

                        </View>
                        </View>
                    </ImageBackground>
                </KeyboardAwareScrollView>
            </ScrollView>
        );
    }
}

const mapStateToProps = state => {
    return {
        phone: state.auth.phone,
        password: state.auth.password,
        device_token: state.auth.device_token,
        http_success: state.helper.http_success,
    };
};

const connectComponent = connect(mapStateToProps, actions)(HomeScreen);
export default reduxForm({ form: 'signIn' })(connectComponent);`

**Comment by mikeerickson** [comment]
I seem to recall there was another issue related to usage with ReactNative, but I have not been able to reproduce the issue (but my ReactNative knowledge is minimal)

I know it may seem “difficult” but any chance you could create a small slimmed down RN app and see if it still happens.  There is a possibility that we have a conflict with other packages, but I can’t say for sure until I get closer to reproducing.

- me

**Comment by xxsnakerxx** [comment]
React native bundler doesn't support dynamic require!

a workaround may be defining a helper method that will be include switch statement like this

```js
_getMessagesDict: function(lang) {
    switch (lang) {
      case 'ru': return require('./lang/ru')
      default: return require('./lang/en')
    }
  },

  /**
   * Load messages (if not already loaded)
   *
   * @param  {string} lang
   * @return {void}
   */
  _load: function(lang) {
    if (!this.messages[lang]) {
      try {
        var rawMessages = this._getMessagesDict(lang);
        this._set(lang, rawMessages);
      } catch (e) {}
    }
  },
```
