### ISSUE TITLE
When this lib will be rewrite with Es6?

### ISSUE THREAD

**Issue by alanhr** [mikeerickson/validatorjs#222]
Hi guys, I like I lot this lib, but it's code is very old and doesn't have a good pattern. Why not rewrite ?

**Comment by iamdtang** [comment]
@mikeerickson what minimum version of Node do you think we should support?

**Comment by mikeerickson** [comment]
@skaterdav85 I am thinking 6.11.5 as it is LTS but only for the current version.  When the ES6 rewrite is complete, I am thinking v8 as there are significant improvements and greatest ES6 support, and will be the next LTS.

https://github.com/nodejs/Release

**Comment by mikeerickson** [comment]
@alanhr old code does not mean a bad product.  It is very stable and feature complete.  Having said that, as I have stated previously I have already embarked on the ES6 rewrite.  

A library of this nature will not offer a great amount of enhancement (other than opportunity to refactor and organize a bit better).  There will not be any significant performance as it just doesn’t lend itself to that type of change.

**Comment by iamdtang** [comment]
@mikeerickson sounds good to me. I think adding a few ES6 features here and there could make the code a little easier to read, which may entice newcomers to help contribute.

**Comment by alanhr** [comment]
@mikeerickson we can use rollup to deliver a good optimized bundle with UMD pattern and add a CLI

**Comment by mikeerickson** [comment]
@alanhr yes, that is what I am using.  But what would the CLI feature include?  I dont see an obvious benefit of a CLI tool?

**Comment by alanhr** [comment]
@mikeerickson in my opinion the CLI can be use to do a deploy for npm when we create a new release  instead of add dist in repository and the another good feature is check the test and cover of code in PR

**Comment by garygreen** [comment]
As Mike has mentioned, we do intend to cleanup the code and modernise it, though it's a big undertaking. I think it would make sense to consolidate all the issues for next version into one so we can scope out what the next major version will look like so everyones on the same page. It may also make sense to do little bits to work towards moderning the code over time rather than a major refactor. Closing for now
