### ISSUE TITLE
Validator is not picking the empty field for validation

### ISSUE THREAD

**Issue by kmahalingpur** [mikeerickson/validatorjs#223]
Hi... If one of the key value is empty then the validator is not picking for validation. The example is below.
Iam not sure its bug or im implementing wrong.

var phone_regx = new RegExp(/^04\d{8}$/g);
var name_regx = new RegExp(/^([a-zA-Z'.-]+ ?)+$/);
var obj={
fname:'',,
lname:"last name",
mobile:"0412312312"
}

Validator.registerAsync('isMandatory', function(value, attribute, req, passes) {  
    if(fieldsOfSection.indexOf(req) !== -1){
      if(mandatoryFieldsOfSection.indexOf(req)!==-1){
        if(value){
          console.log("value:",value,req)//except the empty key all values getting printed
          passes();
        }else{
          passes(false, 'Value required.');
        }
      }else{
      console.log("out:",value,req)
      passes();
    }
    }else{
      passes(false, 'illegal key.');
    }
   
});

validatorSchema={
fname: ['regex:'+name_regx,'isMandatory'],
lname: [ 'regex:'+name_regx,'isMandatory'],
mobile: [ 'regex:'+phone_regx,'isMandatory']
}

var validator = new Validator(appData, validatorSchema.applicantSchema);
            //  call fails()
            validator.fails(function () {
                // Error message:
                appLogger.info(req, validator.errors.all());
                return res.json({ error: "Failed", Result: validator.errors.all() });
            });
            validator.passes(function () {
          //some task
}

**Comment by garygreen** [comment]
You need to have `required` rule otherwise it won't validate.
