### ISSUE TITLE
Is AND OR operation between rules

### ISSUE THREAD

**Issue by kmahalingpur** [mikeerickson/validatorjs#224]
Hi anyone can help me how to perform AND & OR operation.

Thanks in advance :)

**Comment by vict-shevchenko** [comment]
@kmahalingpur can you provide a real-life example of what exactly you validate?

**Comment by pratikt-cuelogic** [comment]
Usecase:
 - in a form lets say I want to implement a usecase where I want to collect atleast one of information from user...
 field A or Field B

**Comment by vict-shevchenko** [comment]
You can use [required_without](https://github.com/skaterdav85/validatorjs#required_withoutfoobar) rule

Plese see a [test](https://github.com/skaterdav85/validatorjs/blob/master/spec/required_without.js) for example.

I also recommend digging into all **required_*** rules.
