### ISSUE TITLE
custom attribute name for arrays

### ISSUE THREAD

**Issue by simontong** [mikeerickson/validatorjs#226]
Is it possible to add attribute names for starred arrays eg.
```js
validator.setAttributeNames({"props.urls.*.name": "URL name"})
```

**Comment by justjuank** [comment]
Hello, any updates on this?

**Comment by mikeerickson** [comment]
@justjuank I must admit, this has fallen through the cracks.  I will get this onto my current review list and advise accordingly.  I wont be able to work on this project until later in the week.

**Comment by justjuank** [comment]
@mikeerickson Thank you, I'll keep an eye on this.

**Comment by tpaksu** [comment]
+1

**Comment by ashfaq1994** [comment]
+1
 validation.setAttributeNames({ "links.*.type": 'type' })???
