### ISSUE TITLE
validatorjs doesn't work with react-native. why ??? 

### ISSUE THREAD

**Issue by drtapha** [mikeerickson/validatorjs#229]
i get the error [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'messages.def')]

**Comment by el-psy-k** [comment]
```javascript
import Validator from 'validatorjs';
import en from 'validatorjs/src/lang/en';

Validator.setMessages('en', en);

const validation = new Validator(data, rules);
```

works for me.

**Comment by drtapha** [comment]
thanks !!!

**Comment by hungdev** [comment]
thank @Javascript-Ninja 
```
import Validator from 'validatorjs';
import en from 'validatorjs/src/lang/en';

Validator.setMessages('en', en);

const validation = new Validator(data, rules);
```

**Comment by vedmant** [comment]
This should have a proper error message, I came across this same issue few times already and each time debugging what's the problem cause the error us just cryptic: "Uncaught TypeError: Cannot read properties of undefined (reading 'def')"
