### ISSUE TITLE
Integer validation passes fractions

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mikeerickson/validatorjs#233]
```

    let expectedBody = {
      user: {
        name: {
          first: 'required|string',
          last: 'required|string'
        },
        username: 'required|string',
        password: 'required|string',
        email: 'required|email',
        mobile: 'required|integer'
      },
      holdingCompanyId: 'required|string'
    };

    let validation = new Validator(req.body, expectedBody);
    if (validation.fails()) return res.status(500).json({ case: 0, message: validation.errors.all() });
```

When I pass `1000.123` for the mobile field, it passes, I expected it to fail, since it's an integer.

**Comment by vict-shevchenko** [comment]
Here are results from running application that uses Validatorjs.

![screen shot 2018-01-23 at 12 47 27 pm](https://user-images.githubusercontent.com/3974306/35271724-ac928714-003b-11e8-804b-660457736384.png)

*`a` stands for `Validator` class. Code is minified.*

So, I think you should double check your setup.

**Comment by mikeerickson** [comment]
@AbdelrahmanHafez As @vict-shevchenko has demonstrated, it should be working as developed.  Could you create a pen (codepen.com, pastebin.com, etc) somewhere with any example code?

**Comment by AbdelrahmanHafez** [comment]
Woah, I just tested it, I could swear it didn't work earlier, now it works as expected, thanks a lot!
