### ISSUE TITLE
Numeric vs Number

### ISSUE THREAD

**Issue by sdr0x07b6** [mikeerickson/validatorjs#235]
For example, the `in` rule.
According to `src/rules.js`, evaluating like this.
`list.indexOf(val[i])`

In HTML input.value, even if it is a number, it is obtained as a character string of numeric, so there is no problem with this.

However, when using Vue, React, etc., obtain the number value as a number value.
Since the value of the rule is a string, the evaluation is always false.

### Current 3.14.2 code

```js
if (val && val instanceof Array) {
  for (i = 0; i < val.length; i++) {
    if (list.indexOf(val[i]) < 0) {
      return false;
    }
  }
}

return true;
```

### As an example, I think that it is possible to change like this

```js
if (val && val instanceof Array) {
  for (i = 0; i < val.length; i++) {
    const exists = list.some(value => {
      const regex = new RegExp(`^${value}$`)
      return regex.test(val[i])
    })
	
    if (!exists) return false
  }
}

return true
```

**Comment by sdr0x07b6** [comment]
I found that custom rules can override preset rules, so I will use that for now (･ω･)
But I'm happy if it will correspond even on the preset side.

**Comment by mikeerickson** [comment]
@sdr0x07b6 thanks for the report and review of code. I am going to add this change to the next release so it will work correctly natively.
