### ISSUE TITLE
Feature request: validate UUID's

### ISSUE THREAD

**Issue by ryuken** [mikeerickson/validatorjs#248]
Hi first of all thanks for this awesome lib!
Im trying to use this lib for everything related to validation.
I use https://github.com/kelektiv/node-uuid for creating UUID's

I found in an issue that there are 2 libs who can be used for UUID validation:
1. https://github.com/mixer/uuid-validate
2. https://github.com/afram/is-uuid

Which one is better or is there a more elegant solution?
I can create a PR if you'd like to include UUID validation into this lib?

**Comment by vict-shevchenko** [comment]
Hi!

I think UUID is a quite specific rule. You can always use a "regex" rule to do such kind of validation. As other option you can split by "-" and use "hex" rule for 5 pars.

**Comment by mikeerickson** [comment]
As @vict-shevchenko stated, this is quite a specific (edge case) rule.  In addition to above, you can also handle this using the custom matchers feature as well.
