### ISSUE TITLE
Required If Example

### ISSUE THREAD

**Issue by ghost** [mikeerickson/validatorjs#252]
Hi everyone,

Is there an example of the required_if rule? It's not clear what `another field` in `required_if:anotherfield,true`should be. Is this the id, name or just a variable? 

I want to use this on a checkbox. I tried name, but it does not work. The checkbox input itself is hidden. 

Thanks for the explanation!
Katia

**Comment by mikeerickson** [comment]
```js
let validation = new Validator({
  cb1: 0,
  cb2: 0
}, {
  cb1: [{ required_if: ['cb2', "checked" }]
});

validation.fails(); // true
validation.passes(); // false
```

```html
<input id="cb1" name="cb2" type="checkbox" value="checked" checked>
```
