### ISSUE TITLE
Support for async/await

### ISSUE THREAD

**Issue by elliotlings** [mikeerickson/validatorjs#253]
Would it be possible to have support for async/await? Makes code a lot tidier!

**Comment by vict-shevchenko** [comment]
Can you provide a more detailed example where you faced a problem with using async/await?

**Comment by mikeerickson** [comment]
While we are always keen to improve this project and provide useful features for our end users, I am curious exactly what you are looking for?

You can easily use validator within an async operation, not sure what you are looking for here?
