### ISSUE TITLE
required_with in array doesn't work (with example code) 

### ISSUE THREAD

**Issue by MikeSuiter** [mikeerickson/validatorjs#255]
We are trying to use required_with in an array and can't get it to work. I created an example and believe it should have errors for options.c but it doesn't. I also tried flattening the rules but it didn't work either. 

[![Edit validatorjs required_with array](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j6mxvj6q5?module=%2Fsrc%2FHello.js)

**Comment by garygreen** [comment]
Closing as old issue, but feel free to reopen if your still experiencing issues.
