### ISSUE TITLE
Is there a rule to allow optional fields

### ISSUE THREAD

**Issue by kiwokiwotiwo** [mikeerickson/validatorjs#256]
Is there a rule to allow optional fields? Meaning only validate the field if it exist

**Comment by vict-shevchenko** [comment]
If I understand your case correctly, consider such example, maybe this can help:

```
const validator = new Validator({},{ name: 'required' });
validator.passes();
```

We can't say return `true`, the name is optional. As you dynamically construct your data object - the same you can construct rules object (`new Validator(data, rules)`).

As other solution, you can review rules from the required section, like `required_with`, `required_without`. Probably some of them can fit your solution.

**Comment by AbdelrahmanHafez** [comment]
I believe the fields are validated only if they exist.

Unless you add `required` if a field doesn't exist it will pass any validation.

**Comment by garygreen** [comment]
Use `present` rule
