### ISSUE TITLE
isMobilePhone true on empty string

### ISSUE THREAD

**Issue by rachaeldawn** [mikeerickson/validatorjs#261]
Behavior: string with 11 spaces returns true as valid phone number
Expected: Returns false
Fix: validation isMobilePhone runs .trim() on string before checking

EDIT

Additional details: I used the locale 'any'

**Comment by mikeerickson** [comment]
In theory it thinks it is correct based on length, but some additional validation through a simple regex should be applied. 

I will get this cured correctly for next update

Thanks for report 😁

**Comment by rachaeldawn** [comment]
@mikeerickson Forgot a potentially important detail. Added it to the original post.
