### ISSUE TITLE
If my data is an array of items, should I validate each individually?

### ISSUE THREAD

**Issue by brandondurham** [mikeerickson/validatorjs#262]
Say I have an array of items like this:

```javascript
[
	{
		item_id: [200132, 200102],
		quantity: 1
	}, {
		item_id: [200132, 200102],
		item_type: "selfHosted",
		self_hosted_pageview_id: 1
	}
]
```

Is the idea that I would validate each of those objects individually and not the collection as a whole?

**Comment by vict-shevchenko** [comment]
Most likely you will have to validate items independently.

But also you can use a [wildcard validation mechanism](https://github.com/skaterdav85/validatorjs#wildcards-rules).

```
new Validator(
{
    data: [
	{
		item_id: [200132, 200102],
		quantity: 1
	}, {
		item_id: [200132, 200102],
		item_type: "selfHosted",
		self_hosted_pageview_id: 1
	}
    ]
}, 
{
    'data.*.item_id': 'array'
    'data.*.quantity': 'required'
})
```

If you specify your question, we can help more.

**Comment by garygreen** [comment]
As vict mentioned, you can use wildcard validation.
