### ISSUE TITLE
Object validation using wildcard

### ISSUE THREAD

**Issue by Ali-Azmoud** [mikeerickson/validatorjs#264]
hi

is there anyway to validate object ( key : value ) using wildcards?

for example take a look at below example:

    const inputs = {
        "name":"Handmade Rubber Sausages",
        "sets":{
        "s0":{
            "stock":"199"
        },
        "s1":{
            "stock":"177",
            "properties":[
                "1",
                "13",
                "21"
            ]
        },
        "s2":{
            "stock":"17",
            "properties":[
                "22"
            ]
        }
    }
    };

    const rules = {
    name: 'required',
    'sets.*.stock': 'required|numeric',
    'sets.*.properties': 'required',
    'sets.*.properties.*': 'numeric',
    };

    let validation = new Validator(inputs, rules);

I tested this and its not working in current version

**Comment by Ali-Azmoud** [comment]
Well, I wrote some piece of code yesterday to **generate** rules based on user objects inputs. then can be used as validatorjs rule

[here you can see the code](https://paste.ofcode.org/YuLkjgDLrgURcB4aMXTv3r)
it's written in ES6.

I hope it helps someone else. :)

**Comment by alanhr** [comment]
Hi, validation wildcard only for array :(
