### ISSUE TITLE
Support ES6 Map as Model

### ISSUE THREAD

**Issue by Metavirulent** [mikeerickson/validatorjs#269]
Currently, the library assumes that data is residing in an object.
However, for generic data, data may as well reside in a Map which should also work without having to convert it to an object every time it needs validation.

**Comment by garygreen** [comment]
This library works both in node and the browser, so we would have to decide to drop support for non-evergreen browsers or improve our build process to target ES5 + ES6. In any case, this would be a big change and likely come with a complete clean of the codebase. Closing for now
