### ISSUE TITLE
docs: Validator.register(...) `requirement` parameter

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mikeerickson/validatorjs#271]
In the Validator.register block, what does the `requirement` parameter represent?

```js
Validator.register('telephone', function(value, requirement, attribute) { // requirement parameter defaults to null
  return value.match(/^\d{3}-\d{3}-\d{4}$/);
}, 'The :attribute phone number is not in the format XXX-XXX-XXXX.');
```

**Comment by vict-shevchenko** [comment]
Not sure, but suppose this deals with rules like "digits:value". Can you check this?

**Comment by AbdelrahmanHafez** [comment]
Well done! That's right.

It needs to be clarified in the documentation.

**Comment by AhmedWaelElsawy** [comment]
despite the issue is closed I didn't find anything about requirement parameter in docs can anyone help with that.

**Comment by mikeerickson** [comment]
@AhmedWaelElsawy The `req` value will contain any information after the semicolon in custom validation rule

With a custom rule as

```js
Validator.register("years", function (val, req, attrs) {
        console.log(val, req, attrs);
        return val.length === parseInt(req)
      });
...
const validator = new Validator({ digits: "2020" }, { digits: "years:4" });
```

When you call execute validator, the `req` parameter would be `4` in this case

====

here is a test from validatorjs project

```js
it("should should handle numeric rule", function () {
  Validator.register("years", function (val, req, attrs) {
    return val.length === parseInt(req);
  });

  const validator = new Validator({ digits: "2020" }, { digits: "years:4" });
  expect(validator.passes()).to.be.true;
});
```

**Comment by AhmedWaelElsawy** [comment]
@mikeerickson thanks very much
