### ISSUE TITLE
Add support for Romanian language

### ISSUE THREAD

**Issue by CosminIonascu** [mikeerickson/validatorjs#276]
I've created a ro.js file where I put all the Romanian translations, I need access to create a pull request,.

Thanks, 
Cosmin

**Comment by vict-shevchenko** [comment]
Hi, @CosminIonascu 

You should fork a project to your account, make changes and create a pull request from your project into source project. 

This links may be useful to you.
https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project 
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Please, close the issue, if things are clear for you.

**Comment by garygreen** [comment]
If you can send a PR for this it would be much appreciated. Closing for now
