### ISSUE TITLE
Validate stringified array

### ISSUE THREAD

**Issue by donpaul120** [mikeerickson/validatorjs#281]
How do i validate an array in string format.

Data being sent to me is a form-data which are mostly string values, however some fields are required to be an array.
{
 "labels":"[\"a\", \"b\"]"
}

I need to be able to validate that labels is an array, how do i go about this using validatorjs?

**Comment by vict-shevchenko** [comment]
I think the best choice in such case it to write your custom validation rule.

**Comment by donpaul120** [comment]
@vict-shevchenko Thanks man, i got this working now with the custom validation rule.

```
this._(this).registerCustomValidators = () => {
     Validator.register("string-array", (value, req, attr) => {
           const [isValid, obj] = Utils.isJson(value);
           return (isValid) ? Array.isArray(obj) : false;
     }, "The :attribute must be a string-array or an array");
 };
```

**Comment by garygreen** [comment]
You can also use wildcards to validate:

```js
var v = new Validator({ arr: [1, 2] }, { arr: 'array', 'arr.*': 'string' });
console.log(v.passes());
console.log(v.errors); 

false
Errors {
  errors:
   { 'arr.0': [ 'The arr.0 must be a string.' ],
     'arr.1': [ 'The arr.1 must be a string.' ] } }
```
