### ISSUE TITLE
Fail on adding extra fields

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mikeerickson/validatorjs#283]
I have the following validation rules, and I am trying to make sure that the data object matches the fields in the validation object, and _only_ the fields in the validation object, so that any extra fields should fail the validation.

My use case here is that I want to sanitize user input along with the validation.
https://github.com/i0natan/nodebestpractices/issues/192

```js
    const expectedBody = {
      quantity: 'required|integer',
      isActive: 'required|boolean'
    };

    const validation = new Validator(req.body, expectedBody);
    if (validation.fails()) {
      return res.status(500).json({ case: 0, message: validation.errors.all() });
    }
```

The current behavior is that when I send this object in the request's body, it passes, but I don't want to allow the user to input the price. Is there a way to achieve this with validatorjs? If not, do you have any recommended libraries that can help with that?

```json
  {
    "quantity": 35,
    "isActive": true,
    "price": 2
  }
```

**Comment by vict-shevchenko** [comment]
In my opinion its better to split your task in two verifications.

1. check that field names match
2. verify field values

for the first one, you won't need a library

```
function doFieldsMatch(request, expected) {
   const requestKeys = Object.keys(request);
   const expectedKeys = Object.keys(expected);

  return requestKeys.lenght === expectedKeys.length && requestKeys.every(key => expectedKeys[key])
}
```

**Comment by AbdelrahmanHafez** [comment]
I tried using something similar for the code snippet above; It worked well until we wanted to handle nested fields, and objects in arrays, etc.

**Comment by AbdelrahmanHafez** [comment]
If anyone's looking at this in the future. As a workaround you can use Joi which has a more strict validation, until this feature is implemented in validatorjs.

**Comment by mikeerickson** [comment]
I am in the process of a rather major overhaul for v4 and will integrate this functionality at that time
