### ISSUE TITLE
Rules for combination of form fields

### ISSUE THREAD

**Issue by crenardy** [mikeerickson/validatorjs#287]
Hi,
I have a use case where I need to validate multiple input fields on multiple pages with dependent values. e.g.
`age: required|integer|min:18`
`weight: required|integer|min:50`
`AND (if age > 70) weight: required|integer|min:65`
Is it possible to declaratively combine rules with dependencies (other than same:xxx)?

I don't really want to introduce custom validators (which is a more functional than declarative approach imho) because of my seconds use case:
In another use case (later in my project) I want to create an editor for creating and extending a given ruleset, so a way to declare and combine these rules would be great. I tried surveyjs, but I wasn't satisfied with the overhead and wanted use mobx.

Any input would be appreciated!

**Comment by vict-shevchenko** [comment]
Hi @crenardy . Looks like the functionality you requesting is not in place. At least I also do not know the solution.

In my case, I analyzed values first, and then dynamically create a rules object. Run validation afterward.

BTW, if you are using mobx, you may find useful a library, that I am working on. [reactive-mobx-form](https://github.com/vict-shevchenko/reactive-mobx-form)
