### ISSUE TITLE
Validation fails but errors are undefined

### ISSUE THREAD

**Issue by iampedii** [mikeerickson/validatorjs#288]
Hi everyone, 
I have the below code which certainly should be failed, it fails but the errors are empty 

```javascript
         const validate = new Validator({
            name: 'D',
            email: 'not an email address.com',
            name2: undefined
         }, {
            name: 'size:3',
            email: 'required|email',
            name2: 'required'
         });
         console.log(validate.fails()); // true
         console.log(validate.errors); // Errors { errors: {} }
         console.log(validate.errors.all()); // []

```

**Comment by vict-shevchenko** [comment]
Hi, you need to check your env config. just checked this on my env. here what I've got:

```
var v = new Validator({
            name: 'D',
            email: 'not an email address.com',
            name2: undefined
         }, {
            name: 'size:3',
            email: 'required|email',
            name2: 'required'
         });

v.fails()
// true

v.errors.all()
/* 
{name: Array(1), email: Array(1), name2: Array(1)}
email: ["The email format is invalid."]
name: ["The name must be 3 characters."]
name2: ["The name2 field is required."]
*/
```

**Comment by Tarpsvo** [comment]
Same issue here. No idea what the issue is - the simplest possible example does not return errors.

```
import Validator from 'validatorjs'

const data = {
  name: undefined,
  email: 'fdsfsd'
}

const rules = {
  name: 'required',
  email: 'required|email'
}

const validation = new Validator(data, rules)

console.info(validation.errorCount) // 0
console.info(validation.errors.all()) // {}
```

**Comment by mikeerickson** [comment]
Hey gang, sorry for delay. I will have a look at this issue later this afternoon (darn day job getting in the way)

**Comment by Tarpsvo** [comment]
Already nailed it. A quick look at the code and the obvious answer was that the `Validator.check()` function is never run. When I called it manually, everything worked as intended.

Alternatively, `fails()` and `passes()` also trigger the `check()` function that populate the errors. I think it should be better documented, even though it makes a lot of sense. :) Thanks!

**Comment by mikeerickson** [comment]
Ah yes, I didn’t even catch that In the example (reading on phone). I will update the documentation to make sure this is clearer.

**Comment by iampedii** [comment]
@Tarpsvo I had the exact same problem and same solution worked for me.

**Comment by garygreen** [comment]
As mentioned, you need to call one of the validation methods to actually validate to get the results.
