### ISSUE TITLE
Functions not works correctly in TypeScript

### ISSUE THREAD

**Issue by coderdiaz** [mikeerickson/validatorjs#289]
Hi, I'm using `validatorjs` in TypeScript but functionality isn't same as in VanillaJS.

The `passes` or `fails` function not resolve with the validation status and the application is blocked in this section.

The function only works with `validator.fails(() => {})` but in the `typing`, the function accept `Function | undefined`.

How can I solve this problem?
Thanks :)

**Comment by mikeerickson** [comment]
@coderdiaz would you please provide some sample code or a fiddle which demonstrates the issue

**Comment by coderdiaz** [comment]
Uhmm.. I solve the issue only reinstalling the package.

**Comment by mikeerickson** [comment]
@coderdiaz well, glad that helped.  I am using the package myself with TypeScript and was stumped as to your issue.  Glad to hear it was resolved.

Note:  I will be making an updated in the very near futures to includes @types

**Comment by coderdiaz** [comment]
Thanks for the coming support typescript's `types` @mikeerickson 🎉
