### ISSUE TITLE
[BUG] Leading zero in 'in:' array 

### ISSUE THREAD

**Issue by ghost** [mikeerickson/validatorjs#291]
Hello there

Is it possible that there is a bug in the 'in:' rule? 
I have a list with values:  ['in:01,02,03,04,05,06,07,08,09,10']
If the value is 10 it works, but when it's a value with a leading zero it doesn't. 

Is there a workaround? 
Thanks!

**Comment by mikeerickson** [comment]
Would you mind submitting some sample code.  Are you wanting the rule to be true (valid) if you test value is 1, 2...9?

**Comment by ghost** [comment]
Yes sure :) it's a bit complex because the rule is set automatically. It works with other fields and other values. I want it to be true with the exact combination '01'. This is the value of the input field. 

`rule: ['integer', 'required', 'in:01,02,03,04,05,06,07,08,09,10,11,12']`

The field is a select and the value is '01' when it fails. When the value is '10' it works. The value needs a leading zero because its a timestamp. 

<img width="165" alt="screen shot 2018-09-11 at 10 02 58" src="https://user-images.githubusercontent.com/5981440/45346728-57fbfd00-b5aa-11e8-829d-0589016abbbd.png">

**Comment by vict-shevchenko** [comment]
Hi @katiasmet !

When you specify rules with parameters in a manner `"in:a,b,c,d"` - validation happens against stringified values `'a', 'b'` etc. So you actually compare `1` ( as `var a = 01; a // 1`) against `'01'` - so getting fail.

If you want to compare integers you need to rewrite your rule as:

uur: ['integer', 'required', {in: [01,02,03,04,05,06,07,08,09,10,11,12]}]

this example works:
```
var validator = new Validator({ uur: 01 }, { uur: ['integer', 'required', { in: [01, 02, 03] }] });
validator.passes();
// > true
```

If this solution is ok for you, please consider closing an issue.

**Comment by ghost** [comment]
Ok thank you! I will check it asap and let you know if it works.
