### ISSUE TITLE
Lang pt_BR may be broken

### ISSUE THREAD

**Issue by CFCSystem** [mikeerickson/validatorjs#299]
I tested other langs but only pt_BR is giving an error.
My code is like this:

```
let Validator = require('validatorjs');
Validator.useLang('pt_BR');
let rules: any = {
            nome: 'required|between:5,100',
            data_nascimento: ['required', 'regex:([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))'],
            cpf: 'required|size:11',
            sexo: 'required|size:1',
            escola_id: 'required'
        }

        let validation = new Validator(aluno, rules);

        validation.setAttributeNames({
            data_nascimento: "data de nascimento",
            escola_id: "escola"
        });

        if (validation.fails()) {
            console.log(validation.errors.all())
        }

```

And the error:
```
Cannot read property 'hasOwnProperty' of undefined
    at Messages._getAttributeName (path/node_modules/validatorjs/src/messages.js:52:41)
    at Messages._replacePlaceholders (path/node_modules/validatorjs/src/messages.js:136:27
```

**Comment by olavoparno** [comment]
Hello, mister @CFCSystem,
We had the same problem here trying to use the Lang method but I came around with a temporary solution, that is to pass an object with all translations (you can copy from the very Lang pt_BR they supply) and pass it as argument as "custom attributes" in the new Validator.

E.g. let validation = new Validator(aluno, rules, { ...customAttributes })

While this is not a real solution, it worked out just fine.

**Comment by brunodesde1987** [comment]
Olá @olavoparno !

Não entendi muito bem a sua solução. 

Como `customAttributes` seria declarado? 🤔

**Comment by olavoparno** [comment]
> Olá @olavoparno !
> 
> Não entendi muito bem a sua solução.
> 
> Como `customAttributes` seria declarado? 🤔

Olá, @solutweb 
talvez eu tenha me expressado mal com o `customAttributes`, na verdade esse objeto seria utilizado para a tradução. É que esse parametro utilizado na construção do Validator é chamado de "custom attribute" se não me engano, portanto esse objeto é mais ou menos uma gambiarra. Ele segue esse formato aqui:

```js
export default { 
  accepted: 'O :attribute deve ser aceito.',
  active_url: 'O :attribute deve conter uma URL válida.',
  after: 'O :attribute deve conter uma data posterior a :date.',
  after_or_equal:
    'O :attribute deve conter uma data superior ou igual a :date.',
  alpha: 'O :attribute deve conter apenas letras.',
  alpha_dash: 'O :attribute deve conter apenas letras, números e traços.',
  alpha_num: 'O :attribute deve conter apenas letras e números .',
  array: 'O :attribute deve conter um array.',
  before: 'O :attribute deve conter uma data anterior a :date.',
  before_or_equal: 'O :attribute deve conter uma data inferior ou igual a :date.'
}
```

Claro que não se atendo apenas a estes atributos acima mas sim aos demais, ex.: e-mail, max, min, etc. Por isso disse que era possível copiar do próprio arquivo de tradução do Validator. 
Obs.: Essa questão toda nem é mais um problema pra nós, acabamos por solucionar de outra forma com muito mais elegância, hahaha.

**Comment by brunodesde1987** [comment]
Ah ok, muito obrigado! 👍 

Consegui resolver substituindo o `Validator.useLang('pt');` por:

```
import pt_BR from 'validatorjs/src/lang/pt_BR';

Validator.setMessages('pt_BR', pt_BR);
```

**Comment by olavoparno** [comment]
@solutweb exatamente isso! 😄

**Comment by jorgermduarte** [comment]
@solutweb , @olavoparno  @CFCSystem  

Posso não vir a tempo, mas de todas as maneiras fiz debug da library e encontrei o problema e a solução.

-> Well, since i got this problem and debugged it, here is the solution in the link below:

Link onde escrevi : https://github.com/skaterdav85/validatorjs/issues/319

**Comment by garygreen** [comment]
Closing in favour of #324

**Comment by mtcarvalho** [comment]
I am a beginner in node, and today I started using this package v3.18.1 with node v12.13.1 and I got same error message as @CFCSystem when trying to use as 

```
const Validator = require("validatorjs");
Validator.useLang("pt_BR");
```

but everything goes well with `Validator.useLang("pt");`. this error was solved or am I missing something?

thanks in advance! :)

**Comment by jorgermduarte** [comment]
@mtcarvalho I checked the resource files. Probably the same problem like last year.
Just add the "attributes : {}" on the pt-br file and it will work.

![image](https://user-images.githubusercontent.com/45755132/82389518-526be100-9a34-11ea-949b-620c6969524d.png)
