### ISSUE TITLE
Placeholder support in async validations

### ISSUE THREAD

**Issue by MatiasOlivera** [mikeerickson/validatorjs#301]
It would be nice to have placeholder support for the attribute name inside the error message returned for the callback in an async validation. This is posible with synchronous validations right now.

### Actual behavior

```javascript
Validator.registerAsync(
  'unique',
  (value, args, attribute, passes) => {
    // database check
    passes(false, 'The :attribute has already been taken.'); // It doesn't work!
  }
);
```

### Expected behavior
```javascript
Validator.registerAsync(
  'unique',
  (value, args, attribute, passes) => {
    // database check
    passes(false, 'The :attribute has already been taken.'); // The username has already been taken.
  }
);
```

**Comment by htv-haitm** [comment]
@MatiasOlivera 
I meets this error when apply the registerAsync.
Would you mind show me your code, please.

`
passes expects a callback when async rules are being tested.;
`

**Comment by MatiasOlivera** [comment]
@haitm-eas Do you want to generate dynamically the error message?

**Comment by htv-haitm** [comment]
@MatiasOlivera 
I want to apply an unique rule which query from DB, and generate dynamically error message.
I don't understand what passes is?

**Comment by htv-haitm** [comment]
@MatiasOlivera 
version 3.15.1, does  support Validator.registerAsync async/await?
It seems does not work for me. 

```
Validatorjs.registerAsync(
      'unique_email',
      async(value: any, args: any, attribute: any, passes: any) => {
        console.log('checkdb begin');
        await Repo.getByEmail(value);
        console.log('checkdb end');
        console.log(value);
        passes();
      },
      'Username has already been taken.',
    );
```

**Comment by MatiasOlivera** [comment]
@haitm-eas I wrote an example showing how to register an async rule in #302.

You can generate the error message dynamically before passing it to `passes` function.

```js
Validator.registerAsync(
  'unique',
  (value, args, attribute, passes) => {
    // database check
    passes(false, `The ${attribute} has already been taken.`);
  }
);
```

You need to pass a callback to `passes` function if the validator has one or more async rules. Related with "Use the same API for sync and async validations" in #303
```js
if (validator.hasAsync) {
  validator.passes(() => {
    // success
  });
  validator.fails(() => {
    // failure
    const errors = validator.errors.all();
  });
}
```

**Comment by htv-haitm** [comment]
@MatiasOlivera 
May i use async/await in version 3.15.1 (https://github.com/skaterdav85/validatorjs/tree/v3.15.1)?
I cannot using async validator rule althought i have read your example #302.

**Comment by MatiasOlivera** [comment]
@haitm-eas There isn't `async/await` support, but you could use a promise. Can you create a new `issue` asking for help? This conversation isn't related to the topic in the first comment.

**Comment by htv-haitm** [comment]
@MatiasOlivera 
How is about this [example](https://github.com/skaterdav85/validatorjs/blob/7675348d0b6947ec5b4fcde18d6e5c518ac218ce/README.md) ? The is an async/await define from your example.

**Comment by MatiasOlivera** [comment]
@haitm-eas The example is showing how to make an async rule using promises, not `async/await`. The callback is a normal function, not an async function.
