### ISSUE TITLE
Package is ~200kb when using Webpack

### ISSUE THREAD

**Issue by phegman** [mikeerickson/validatorjs#306]
Wondering if anybody can shed some light on what might be going on here. When I use this package with Webpack it ends up being ~200kb. `validator.min.js` is only ~20kb so it appears it isn't bundling correctly. 

I can reproduce this in [Create React App](https://github.com/facebook/create-react-app) and [Preact CLI](https://github.com/developit/preact-cli). If you spin up a fresh app in either of these and then compare the build files before and after importing this package it is about 200kb larger. 

Thanks in advance for any insight and thanks for building a great package!

**Comment by ivan-work** [comment]
You might want to look at #220 I think you have the same problem

**Comment by phegman** [comment]
Thanks, that was the issue! The package is now ~20kb which is perfect!

Thanks again for a great package!
