### ISSUE TITLE
Warn if some arg isn't an object

### ISSUE THREAD

**Issue by MatiasOlivera** [mikeerickson/validatorjs#309]
It's possible to pass a string to the rules parameter.

```js
var Validator = require('validatorjs');

const data = 'John';
const rules = 'required';
const validation = new Validator(data, rules);
const errors = validation.errors.all(); // ​​​{ undefined: [ 'The undefined field is required.' ] }​​​​​
```

And you can make pass the validation in this way:

```js
var Validator = require('validatorjs');

const data = { undefined: 'John' };
const rules = 'required';
const validation = new Validator(data, rules);
cont passes = validation.passes(); // true
```

It would be nice to have some warning that tells us that the arguments aren't valid.

**Comment by garygreen** [comment]
It looks odd, but it's still technically a valid data object. It's not practical to warn about invalid arguments passed to every function - but if we did switch to Typescript or something like that in the future it may help improve this. Closing for now

**Comment by MatiasOlivera** [comment]
> it's still technically a valid data object.

The variable `rules `is not valid. It should thrown an error

> It's not practical to warn about invalid arguments passed to every function

But it can save time for some people if they pass the wrong data type

> we did switch to Typescript

Yes, that could help but what happens if you are only using javascript?

**Comment by vict-shevchenko** [comment]
As an option for future enhancement, this property verification can be in dev build but may be absent in prod one.
