### ISSUE TITLE
How to return validation.errors.all() in validation.fails ?

### ISSUE THREAD

**Issue by suhardiyan** [mikeerickson/validatorjs#311]
How can I return validation.fails from registerAsync function ?

```
let asd = await validation.fails(async function () {
 return await validation.errors.all();
});
console.log(asd)
```

asd still undefined, 

still trying using promise

```
		let asd = await validation.fails(() => {
			return new Promise((resolve, reject) => {
				return resolve(validation.errors.all());
				}).then((state) => {
					// console.log(state)
				})
				.catch((error) => {
					resolve(error);
					// console.log(error)
				});
			});

		console.log(asd)
```

still asd undefined

All I want is to store validation.errors.all() to asd, so I can pass asd return to my controller function. Im using "validatorjs": "^3.15.1"

How can I achieve that?

anyhelp will appreciate

**Comment by vict-shevchenko** [comment]
You are getting an `undefined` as `validation.fail` is not registered as `async` function (does not return Promise)

You may want to do something like this (and also test this with a debugger, the code may not work, but hopefully explains a concept) 

```
let asd = await new Promise((resolve, reject) => {
  validator.fails(function() {
    resolve(validator.errors.all());
  });
});

console.log(asd)
```

**Comment by suhardiyan** [comment]
Thanks for the reply @vict-shevchenko , your code is works, but if validator has no fail, it will turn unresponsive request/infinite request/no-ending request..

How can I handle that? because i trying to give handling `if (validation.fails())` the code seems not works 

> InternalServerError: fails expects a callback when async rules are being tested.

It should be true or false right?
