### ISSUE TITLE
Validator.useLang("pt") and pt-br Error and the Solution !

### ISSUE THREAD

**Issue by jorgermduarte** [mikeerickson/validatorjs#319]
I debuged the respective error and found the solution:
 - The error occurres because u didn't added the "attributes : {}"  property in the validatorjs/src/lang/pt.js

**Comment by jorgermduarte** [comment]
![imagem](https://user-images.githubusercontent.com/45755132/53823941-b1962080-3f6a-11e9-93d1-dc06a6e31257.png)

**Comment by jorgermduarte** [comment]
Sended a commit with all the languages detected with the same problem.

**Comment by garygreen** [comment]
Closing in favour of #324
