### ISSUE TITLE
Not ES5 valid

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#325]
I'm unaware of how long this has been an issue, but in `rules.js` we're using ES6 getter for one function which makes the build broken for ES5 targets:

https://github.com/skaterdav85/validatorjs/blob/decc8ceb69aa47b7c44168acec2b3c4da926f798/src/rules.js#L551

**Comment by mikeerickson** [comment]
Wow, this is some 2 years old.  Tells me a couple of things

1. not many of our users are using ES5 anymore
2. surprised it took this long to notice

I guess we can make a patch fix as we await v4, but seemingly not a real show stopper

@garygreen Do you want to submit a PR for this as it is your report (assuming you have a personal need for it)
