### ISSUE TITLE
fails() is true when processing a rule without matching input value 

### ISSUE THREAD

**Issue by alexkaraman85** [mikeerickson/validatorjs#33]
Hi,

Today I noticed that while validating a rule without a matching input value it is possible to get a fail state.  At the moment, in my situation, it would be preferable to have the validation pass in such a situation.   However, Im not really sure of why a validation should fail if a rule exists, but not the matching input value.  It seems like it should be possible to have a rules list that contains validations that should not be executed for every validation.  For instance if I have a common validation json that I want to be used for the entire project.

Please let me know if Im thinking in the wrong direction.

**Comment by iamdtang** [comment]
Hi Alex,

Thanks for the feedback. I think in some cases you'd want it to fail and others you would not. For example, the following I typically want to fail.

``` js
var validation = new Validator({}, { name: 'required' });
```

I definitely see your point too though. What you could do instead would be to create a custom rules object based on your validation json. Something like:

``` js
var rules = {
   nameValidation: 'required'
};

var validation = new Validator({}, { name: nameValidation });
```

I looked at how Laravel does it and they too fail in this scenario:

``` php
$validation = Validator::make([], [ 'name' => 'required' ]);
dd($validation->fails()); // true
```

**Comment by garygreen** [comment]
It shouldn't fail unless your using the required rule. @alexkaraman85 can you provide code example or is this no longer an issue?

**Comment by garygreen** [comment]
@alexkaraman85 please create a new issue if you need anymore assistance.
