### ISSUE TITLE
Doc description of size misses array

### ISSUE THREAD

**Issue by ryuken** [mikeerickson/validatorjs#331]
**size:value**
_The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value._

Above is the current explanation for size.
It misses something like: For Array data, value corresponds to Array.length.

I had to search if size only worked with string and numbers and not with Arrays.
**this.getSize** is called which returns the Array.length

**Comment by mikeerickson** [comment]
Added to 3.16 release
