### ISSUE TITLE
Generate random input based on validatorjs rules

### ISSUE THREAD

**Issue by shuhailshuvo** [mikeerickson/validatorjs#333]
**Labels**: [question] or [feature]

Hi,
I just want to know if there is any option for generating mock/fake input based on rules.
Say, I've a field `userName`. and validatorjs rule is `required|string|size:5`.

I need a method like this
`mock('userName', 'required|string|size:5')`

that might return `alpha` or `qwert` or `abcde`

Please let me know if there is any other library that generate mock by validatorjs rules.

Thanks.

**Comment by mikeerickson** [comment]
This can be accomplished using the Faker library
