### ISSUE TITLE
Custom rules are not registering.

### ISSUE THREAD

**Issue by ghost** [mikeerickson/validatorjs#334]
Hello, I have an issue where my custom validation rules are not registering. TO give a little backstory, our app was using validatorjs locally and everything worked just fine. The structure was this:
index.js
ProfileValidator.js

In the index file, is where I declared my custom validations, and then I used them in the ProfileValidator. However, when I moved everything to its onw seperate git and used npm to call it in, the custom validations no longer work. Also bundler is rollup on the git that I set up for the validation library. If any of this makes sense let me know where I might have messed up. Or, it might be possible that the bundle is effecting the functionally.

**Comment by mikeerickson** [comment]
@sselke could you provide a code sample, or better yet a sample app on git where I can test locally.  Very hard to debug without seeing code

**Comment by zanedev** [comment]
I had the same issue, [this issue fixed it](https://github.com/skaterdav85/validatorjs/issues/229), setting the messages to `en`, not sure why that mattered once it was npm linked in a different project.

**Comment by ghost** [comment]
Thank you Zane, closing the issue.
