### ISSUE TITLE
Note for date parsing

### ISSUE THREAD

**Issue by tpaksu** [mikeerickson/validatorjs#338]
Hello all, 

This is not a bug report, this is a heads-up message for people those run into this situation.

One of my clients recently told me that the date validations always gives error in iPhones and I started to check the reason, and it came out that date comparisons in safari need a different format than the standards accepted by other browsers. 

For example `yyyy-mm-dd hh:ii:ss` is not a valid format for safari. It should be formatted like `yyyy-mm-dd[T]hh:ii:ss[Z]` to be accepted in all browsers. 

Keep that in mind. There's nothing to change inside the validator.js code because it's needed to be done outside the library.

Thanks for the great library!

**Comment by mikeerickson** [comment]
@tpaksu thank you for the notice, much appreciated.  I will add some information to the documentation about this.  Do these validation rules work outside of safari on iOS?

**Comment by tpaksu** [comment]
Yes, they do with the browser's default supported date formats. Just found these: 

http://dygraphs.com/date-formats.html
https://stackoverflow.com/questions/16250514/which-javascript-date-format-is-compatible-with-all-browsers

**Comment by tpaksu** [comment]
Just realized it doesn't include Safari either. Will need to run some tests like dygraphs for safari and post the results. But I don't have an apple device :/

**Comment by mikeerickson** [comment]
I will run some additional tests here as we have Apple devices to test with

**Comment by tpaksu** [comment]
Ok, but how can we ensure that the user puts in a valid formatted date for `new Date()`? Putting a compatibility table for users doesn't seem to be a right way IMHO. Maybe an extra parameter for specifying a format would be useful but plain javascript doesn't support that I guess. Will need a library to do the parsing. Complicated..

**Comment by tpaksu** [comment]
Also check this: https://stackoverflow.com/a/4310986/916000
