### ISSUE TITLE
Make NPM package smaller

### ISSUE THREAD

**Issue by mhammerc** [mikeerickson/validatorjs#339]
Hello! Your package looks great, thank you for the work.

I installed it using npm. Here is the package size:

<img width="140" alt="image" src="https://user-images.githubusercontent.com/5982507/63649249-9fd44f80-c73b-11e9-9cdc-cde2dc2de7c7.png">

I see lots of things are shipped, including tests and minified versions. I don't know how bower works and more, but could the package be made smaller using .npmignore?

**Comment by mikeerickson** [comment]
I have this on my list of things to include in the 4.0 release.

**Comment by mhammerc** [comment]
Thanks!
