### ISSUE TITLE
[poll] validatorjs and browser support via script tag

### ISSUE THREAD

**Issue by mikeerickson** [mikeerickson/validatorjs#342]
As we are preparing `validatorjs` v4, we are faced with the decision to suspend support for using `validatorjs` with `<script>` tag in the browser.

So, I will put it to you all...

Do you still use UMD format?

**Comment by ryuken** [comment]
i don't use it via script tag, if i use it on the front-end it gets there via webpack

**Comment by GeorgeWL** [comment]
not everyone uses webpack, some try to stick with pure javascript with as few modules as possible.

**Comment by tpaksu** [comment]
As many out there, I would like to continue using this package on, for example my wordpress development, or my single-paged website which only contains a contact form etc. that may not contain any module loaders/bundlers. Not every case with javascript includes a module loader/bundler.

**Comment by vict-shevchenko** [comment]
I am not completely familiar but there is something like UMD that allows the code be bundled and used as a script tag simultaneously.
