### ISSUE TITLE
Numeric trims leading + symbols

### ISSUE THREAD

**Issue by craigblunden** [mikeerickson/validatorjs#347]
In the numeric ruleset, the value is passed through a Number() function which apparently trims leading + symbols. 

https://github.com/skaterdav85/validatorjs/blob/master/src/rules.js#L186
Number('+0400') returns 400 

Perhaps an alternative would be using regex if decimals shouldn't be taken into account?
const reg = /^\d+$/;
reg.test('0400') // true
reg.test('0 400') // false
reg.test('0.400') // false
reg.test('+0400') // false

**Comment by mikeerickson** [comment]
@craigblunden I am going to see about adding this in the 3.19 release

**Comment by mikeerickson** [comment]
@craigblunden After further review, I believe this would be better served as a custom rule.  Making the above change could have potential negative breaking changes for existing applications.
