### ISSUE TITLE
isMobilePhone method is not working with kh(Cambodia) number well

### ISSUE THREAD

**Issue by mengheangrat** [mikeerickson/validatorjs#351]
Cambodia carries has two type of phone number `+85570123456` and `+855961234567` 
Issue: 
- it cannot validate with `+855961234567` kind.

**Comment by mikeerickson** [comment]
@mengheangrat Would you mind showing the code you are using to perform you phone validation? This package does not have native support for phone numbers, they are typically added as custom rules?

All native validatorjs rules can be found here

https://github.com/skaterdav85/validatorjs#available-rules

Further, there is no method `isMobilePhone` contained in validatorjs, thus I am thinking you (or someone) has created a custom rule
