### ISSUE TITLE
Uncaught TypeError: parseISO is not a function

### ISSUE THREAD

**Issue by okamuuu** [mikeerickson/validatorjs#357]
I want to use this library in a Browser like a Nuxtjs. But I got an error message when I specify 'date' rule. It looks like the require statement return, not parseISO function, but Module object contains default property is parseISO function.

<img width="1040" alt="スクリーンショット 2020-02-18 10 44 38" src="https://user-images.githubusercontent.com/123702/74697426-02675d80-523e-11ea-8563-f2ccb9aae441.png">

Do you have any solutions?

## How to reproduce

```
mkdir parce-validatorjs-test && cd $_
yarn init -y
yarn add validatorjs
touch index.html index.js
```
edit index.html

```
<html>
 <body>
  <script src="./index.js"></script>
 </body>
</html>
```

edit index.js

```
import Validator from 'validatorjs'
const v = new Validator({today: '2020-02-18'}, {today: 'date'});
v.passes()
```

Run parcel. That's it.
 
```
parcel index.html
```

## Here are my environments:

```
% sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76

% node -v
v12.16.0

% parcel --version
1.12.4
```

**Comment by mikeerickson** [comment]
I have to try out your specific use case, but won’t be able to look at this until later this week

In the meantime, you can address by:

yarn add date-fns 

I have used our projects a LOT in other applications which I build with webpack, but have not used with parcel 

— mike

**Comment by mikeerickson** [comment]
I am not quite sure why yarn didn’t install date-fns to begin with? Does the module exist in node_modules directory (before you try adding) I am not sure if this is a parcel issue or not...

**Comment by okamuuu** [comment]
Thank you for the reply. Not in a hurry so far, because I'm avoiding that problem by providing my function for now.

```
import { isValid as isValidDate, parseISO } from 'date-fns'

Validator.register(
  'birthday',
  value => value.length === 10 && isValidDate(parseISO(value)),
)
```

But I don't like to write such a redefined function. If anyone knows this solution, please tell me that:)

PS. This problem also occurs in Nuxt.js

**Comment by mikeerickson** [comment]
@okamuuu So, are you saying the problem only occurs when using the `birthday` function?

**Comment by okamuuu** [comment]
the following codes occurs the problem.

```
import Validator from 'validatorjs'
const data = { 
  birthday: '2020-02-18',
}
const rules = { 
  birthday: 'required|date', <= I expected this works but it doesn't
}
const v = new Validator(data, rules)
v.passes()
```

So I add a custom rule

```diff
 import Validator from 'validatorjs'
+import { isValid as isValidDate, parseISO } from 'date-fns'
+
 const data = { 
   birthday: '2020-02-18',
 }
 const rules = { 
-  birthday: 'required|date', // <= I expected this works but it doesn't
+  birthday: 'required|birthday',  // <= so, I add custome rule named birthday
 }
+
+Validator.register(
+  'birthday',
+  value => value.length === 10 && isValidDate(parseISO(value)),
+)
+
 const v = new Validator(data, rules)
```

**Comment by okamuuu** [comment]
I found one of the solutions:)

```diff
-import Validator from 'validatorjs'
+import Validator from 'validatorjs/dist/validator'
```

If possible, how about the following changes in package.json?

```diff
- "main": "./src/validator.js",
+ "main": "./dist/validator.js",
```

@mikeerickson 
<del>I've already resolved my problem so that you can close this issue.</del>
And thank you for replying though you're busy:)

**Comment by okamuuu** [comment]
I see... `./dist/validator.js` does't contain language set...

**Comment by MiroslavPetrik** [comment]
I have the same issue in the `isValidDate` function while using the v3.18.1 

```
var parseISO = __webpack_require__(/*! date-fns/parseISO */ "./node_modules/validatorjs/node_modules/date-fns/esm/parseISO/index.js");

function leapYear(year) {
  return year % 4 === 0 && year % 100 !== 0 || year % 400 === 0;
}

function isValidDate(inDate) {
  if (inDate instanceof Date) {
    return !isNaN(inDate);
  } // reformat if supplied as mm.dd.yyyy (period delimiter)


  if (typeof inDate === 'string') {
    var pos = inDate.indexOf('.');

    if (pos > 0 && pos <= 6) {
      inDate = inDate.replace(/\./g, '-');
    } // if date is mm-dd-yyyy or yyyy-mm-dd


    if (inDate.length === 10) {
      return isValid(parseISO(inDate));
    }
  }
```

**Comment by mikeerickson** [comment]
Can you please confirm the version you are using.

**Comment by MiroslavPetrik** [comment]
v3.18.1

**Comment by syabro** [comment]
Same here, 3.18.1, webpack

**Comment by mikeerickson** [comment]
Unfortunately, I am not in a position to work on this right now, and likely not until this country opens again and we can all start working our jobs.

**Comment by okamuuu** [comment]
I already solved this problem in another way to implement the function by myself.

I think that "es6 import/export" mixed with "require/modules.exports" cause of this problem

I'm not sure how to write correctly .babelrc in this case, but it was easy for me to rewrite the date validation rule.

If you guys meet the same situation, you can solve the same way. So this issue can be closed, my opinion:)

**Comment by mikeerickson** [comment]
Thank you for the information.
