### ISSUE TITLE
Add custom validation rule

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#36]
Any docs on how to do this? Is it just `Validator.prototype.validate.my_custom_rule = function() { ... }` ?

Would be cool to be able to do like in Laravel:

``` js
Validator.extend('my_custom_rule', ...);
```

**Comment by garygreen** [comment]
Nevermine, half asleep it seems. Was looking for `register`

**Comment by iamdtang** [comment]
Glad you found it =)
