### ISSUE TITLE
String length control rules always pass on empty strings

### ISSUE THREAD

**Issue by marko-ogg** [mikeerickson/validatorjs#363]
Following rules always pass on empty string, no matter what is the rule (min,max) value:

- between:min,max
- digits:value
- digits_between:min,max
- min:value

For example, if you assign empty string to variable "name", and then add rule **min:3** to it, it will pass.

**Comment by agougousis** [comment]
I have the same problem with empty strings. 

I tried the following code with Node version v8.9.4 

```
let Validator = require('validatorjs');

const inputValues = {
  phoneNumber: '',
};

const validationRules = {
      phoneNumber: 'string|min:5,
};

const validationResult = new Validator(inputValues, validationRules);
const passes = validationResult.passes();

console.log('-----------------------');
console.log('Passes validation: ' + passes);
```

It passes.
I would expect it to fail.

**Comment by PHILLIPS71** [comment]
I'm also running into this issue, I'd too expect this to fail validation

**Comment by mikeerickson** [comment]
To all, are you thinking that `null` string should pass, but an empty string (with appropriate `min` rule) should pass?

- if string null, pass
- if empty string, fail

**Comment by mikeerickson** [comment]
@PHILLIPS71 @agougousis Hey gang, if you are still having issues, please let me know. Otherwise I will close this issue accordingly.
