### ISSUE TITLE
Feature: Validate IP

### ISSUE THREAD

**Issue by CSenshi** [mikeerickson/validatorjs#365]
I suggest validating IP addresses, IPv4 as well as IPv6. Laravel's validator has this feature, I think it will be awesome if we had IP validator in this project

**Comment by CSenshi** [comment]
I would love to work on this if you agree on this feature :)

**Comment by mikeerickson** [comment]
@CSenshi Thank you for your contribution, I have added this to the forthcoming 3.19 release (should be published tomorrow)
