### ISSUE TITLE
Not_in not working

### ISSUE THREAD

**Issue by azayas97** [mikeerickson/validatorjs#368]
Hello, I'm trying to check if the name of a product is already on the database.
So what I'm doing is using _not_in_ the same way I use _unique_ on Laravel, but the problem is that it just doesn't work, am I using it wrong?

Here's an example of how I am using not_in.
```
const validationRule = { 
    name: 'required|string|max:100|not_in:products',
    price: 'required|numeric'
};
```

Thanks.

**Comment by mikeerickson** [comment]
@azayas97 unlike Laravel validation, which occurs on the server side, validatorJS is client side and does not have same database access.  

You would have to create a customer rule which would execute an AJAX request to the server to perform your desired validation.  In is really impossible for us to provide this functionality in ValidatorJS core as we don’t have any knowledge of your database.
