### ISSUE TITLE
Asynchronous validation

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#37]
Currently this library only supports synchronous validation. The nature of javascript is pretty asynchronous so it's definitely a worthwhile feature to have.

For instance, you could have a `username_available` validation rule which performs an ajax check for availability of the username. 

I'm not sure what architectural changes would be needed for this, but I think possibly just a case of adding some functions `passesAsync()` `failsAsync()` which returns a promise, along with promise support when calling the actual validators? Or maybe change the validator so it supports async by default (would be breaking change but would simplify and be a single-entry point for validation logic).

``` javascript
validator.passes(function() {
 // Yipee!
});

validator.fails(function(errors) {
 // Waa
});
```

**Comment by iamdtang** [comment]
This would definitely be useful. I'll have to think about this for a little. I would like to keep the synchronous API the same to ensure backwards compatibility. Ideally, in the event that 1 or more async rules are passed into `new Validator()`, then you could pass in callbacks to `passes()` and `fails()` like you mentioned above which would get invoked when all asynchronous requests have completed. The implementation also needs to be promise library agnostic since this library can be used in the node environment. 

What do you think of the following API? 

``` js
Validator.registerAsync('username_available', function(value, requirement, attribute) { 
    return function(passes, fails) {
        return $.ajax({
            url: '/some-user-lookup'
        }).then(function() {
            passes();
        }, function() {
            fails();
        });
    };
}, 'The :attribute is not available.');
```

**Comment by garygreen** [comment]
That looks awesome mate. Just a few things to consider:

Having two different ways of determining passing/failing might catch a few people out if they don't realise that some of the rules they're testing against is async. One way around this could be to just detect if the validator has async rules `.hasAsyncRules()` and if so, check to see if a callback has been passed to `passes` and `fails` and `throw` an uber short warning message `validator is async, <method:passes/fails> needs a callback`.
Also if a callback has been supplied to `passes()` or `fails()` it should ALWAYS work and invoke the callback, if even no async rules. Personally I'll always use the validator that way, as it is the best of both worlds without any gotchas.

For the error messages in async, ideally there should be a nice way to supply a custom error message. For instance, my `username_available` async rule checks a few things and will return the error message (400 Bad Request) `Username has already been taken` or `Username is reserved`, else returns 200 if all ok. Something like that below would be nice and simple. If you supply a custom error message when calling the `fails` callback it will use that one, if not it will default to the one supplied in the `registerAsync`.

```
Validator.registerAsync('username_available', function(value, requirement, attribute) { 
    return function(passes, fails) {
        return $.ajax({
            url: '/some-user-lookup'
        }).then(function() {
            passes();
        }, function(xhr) {
            fails(xhr.responseJSON.error_message);
        });
    };
}, 'The :attribute is not available.');
```

**Comment by garygreen** [comment]
@skaterdav85 anymore thoughts on this?

**Comment by tifidy** [comment]
I tried the database querying on db but passes() gets fired before my call finishes. This causes my request to get stuck without a respond. implementing async is a must. Becuase database validation would be really nice feature in this validation plugin.

```
Validator.register('unique', function(value, requirement, attribute) { 
var reqs = requirement.split(",");
var query = {};
query[reqs[0]] = value;
var result;
User.findOne(query).exec(function(err, docs){
    result = docs; 
});
return setTimeout(function () {
  if(result.length>0)
{
            //BULUNDU
            return false;

}
else
{
            return true;

}
}, 100)



}, 'email already exists.');
```

**Comment by garygreen** [comment]
@Oguzhanpiskin It's on my top priority list next, will be in version 2.0

**Comment by garygreen** [comment]
Just looking into this now. Have got a working implementation, just getting the tests all working now. Asynchronous is such a pain in jasmine, so tempted just to switch everything to mocha. Do you have any strong preference for jasmine over mocha @skaterdav85 ?

**Comment by iamdtang** [comment]
Ah ya this project still runs on Jasmine 1. I am indifferent to either but asynchronous testing in Jasmine 2 is the same as in Mocha. I think switching to Jasmine 2 might be less work if any of the tests are using Jasmine spies.

**Comment by garygreen** [comment]
Just trying out jasmine 2, getting some weird issues where it cuts out half way through tests. Can't figure it out. I'll push what I got for async so far, would be grateful if you could take a look :)

**Comment by iamdtang** [comment]
Heh, I wrote a blog post about upgrading not too long ago. http://thejsguy.com/2015/01/29/Upgrading-Jasmine-from-1.3-to-2.1.html

**Comment by garygreen** [comment]
Interesting! Most of the tests are pretty basic so I haven't come across any that needed changing to support jasmine 2.0 so far.... maybe I missed something? Heres the PR #53

**Comment by garygreen** [comment]
I've switched all tests to using mocha, having much more success than Jasmine. Tests seem to be faster too which is nice.

**Comment by iamdtang** [comment]
great! thanks!
