### ISSUE TITLE
Property 'attributes' missing on pt_BR lang

### ISSUE THREAD

**Issue by damews** [mikeerickson/validatorjs#370]
Tried to validate an property with **in** rule and a undefined error was caused

_Cannot read property 'hasOwnProperty' of undefined
messages.js:52:41_

I checked other lang files ('en', 'ru', etc) and that ones have the 'attributes' property with a empty object.

**Comment by mikeerickson** [comment]
@LiserLine ya we have cleared up all the language files and have missing attribute. We had some commits messed up so we broke a few different languages. 

We have a new build prepped which will be released to the wild early next week
