### ISSUE TITLE
Not working in Nestjs 

### ISSUE THREAD

**Issue by menkaff** [mikeerickson/validatorjs#373]
After installing in Nestjs this error thrown 
[ExceptionsHandler] validatorjs_1.default is not a constructor
this is my code & i use it in service of Nestjs 

         let data = {
            name: 'John',
            email: 'johndoe@gmail.com',
            age: 28
        };

        let rules = {
            name: 'required',
            email: 'required|email',
            age: 'min:18'
        };

        let validation = new Validator(data, rules);

**Comment by alanhr** [comment]
Hello @menkaff, how you import the validator in Nestjs ?

Could you try to something like `import {Validator} from 'validatorjs'`?

**Comment by menkaff** [comment]
I imported it exactly like your doc 
Like this
`import {Validator} from 'validatorjs'
`

**Comment by alanhr** [comment]
@menkaff  I made a test in [codesandbox](https://codesandbox.io/s/polished-haze-e96yd?file=/src/index.ts) and everything works.

**Comment by menkaff** [comment]
I imported like this
`import Validator from 'validatorjs';` as documentation
and this error thrown
[ExceptionsHandler] validatorjs_1.default is not a constructor
and now also import it like this but again another error thrown.
`import { Validator } from 'validatorjs';`
[ExceptionsHandler] validatorjs_1.Validator is not a constructor
and i also import in service file of Nestjs
I think the problem is how to use it with nestjs not Typescript as your sandbox works properly

**Comment by mikeerickson** [comment]
Hey @menkaff 
 
There are two ways to solve this:


Use CommonJS format:

```js
const Validator = require(‘validatorjs’)
```

Or, if you prefer to use ESM format, you can use

```js
import * as Validator from 'validatorjs';
```

Since ValidatorJS does not currently have TypeScript definitions (this will be added in the next major version), to get it working with TS you need to use the `import * ...` format (which is of the same for any commonJS module that does not have TS definitions

Here is the modified `app.services.ts` file which shows this working

```ts

import { Injectable } from '@nestjs/common';
import * as Validator from 'validatorjs';

@Injectable()
export class AppService {
  getHello(): string {
    const data = {
      name: 'John',
      email: 'johndoe@gmail.com',
      age: 28,
    };

    const rules = {
      name: 'required',
      email: 'required|email',
      age: 'min:18',
    };

    const validation = new Validator(data, rules);

    const passes = validation.passes(); // true
    const fails = validation.fails(); // false

    return `Passes: ${passes} <br> Fails: ${fails}`;
  }
}

```

**Comment by menkaff** [comment]
Hi @mikeerickson thanks for your solution , I implement ESM format and now it's working properly.
