### ISSUE TITLE
Need Help on validating array of objects

### ISSUE THREAD

**Issue by sridhar-v9** [mikeerickson/validatorjs#374]
### Sample code snippet

```
var data = {
      users: [
        {
          name: "Sample",
          bio: {
            age: 28,
            education: {
              primary: 'Elementary School',
              secondary: 'Secondary School'
            }
          }
        },
        {
          name: undefined,
          bio: {
            age: 28,
            education: {
              primary: 'Elementary School',
              secondary: 'Secondary School'
            }
          }
        }
      ]
    }
```  
### Rules

```
    var rules = {
      'users.*.name': 'required',
      'users.*.bio.age': 'min:18',
      'users.*.bio.education.primary': 'string',
      'users.*.bio.education.secondary': 'string'
    }
```
### Validate code

```
   var validation = new Validator(data, rules);
    validation.fails();
```

### output

```
{"errors":{"users.1.name":["The users.1.name field is required."]}}
```
 the above output is correct because i wrote a generic rule to see in each "user" object check "name" is present/not

but i want to check any one of the 'user' object 'name is present/not in that array. Not Sure how to accomplish this... 

Please advice on the same .. Thanks in advance

**Comment by mikeerickson** [comment]
Hello @sridhar-v9 

We currently do not have native support for what you are looking for, however, this can be handled with a custom validator.

```js

      Validator.register(
        "validUserName",
        function(values, requirement, attribute) {
          let valid = false;
          values.forEach((value)=> {
            if((value.name) && (value.name.length>0)){
              valid = true;
            }
          });
          return valid;
        },
        "The :attribute name is required"
      );

      let data = {
        users: [
          {name: "mike"},
          {name: null}
        ]
      };

      let rules = {
        'users': 'validUserName'
      };

      let validation = new Validator(data, rules);
      validation.passes() // will be true

```

**Comment by iedmrc** [comment]
> Hello @sridhar-v9
> 
> We currently have native support for what you are looking for, however, this can be handled with a custom validator.
> 
> ```js
>       Validator.register(
>         "validUserName",
>         function(values, requirement, attribute) {
>           let valid = false;
>           values.forEach((value)=> {
>             if((value.name) && (value.name.length>0)){
>               valid = true;
>             }
>           });
>           return valid;
>         },
>         "The :attribute name is required"
>       );
> 
>       let data = {
>         users: [
>           {name: "mike"},
>           {name: null}
>         ]
>       };
> 
>       let rules = {
>         'users': 'validUserName'
>       };
> 
>       let validation = new Validator(data, rules);
>       validation.passes() // will be true
> ```

@mikeerickson  what is the native version of validating an array of values?

Is there something like below:
```javascript
rules = {
  users: [{
    name: 'required|alpha',
    age: 'required|min:18'
  }]
}
```

**Comment by mikeerickson** [comment]
@iedmrc as documented above, we do NOT have native support for what you are trying to accomplish and you would be best served using a custom validator which iterates through each array item and perform a one off validation.

**Comment by iedmrc** [comment]
Thanks @mikeerickson for the answer!

I think you should update the above comment because it's written `We currently have native support for what you are looking for ...`.

**Comment by mikeerickson** [comment]
@iedmrc my apologies for the confusion. I have edited the initial comment accordingly
