### ISSUE TITLE
Introducing dominar.js

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#38]
Not strictly an 'issue' but thought I'd share with you a library I've built on-top of this brilliant validator.js.

https://github.com/garygreen/dominar

It's in very early prototype stages so lots of work still to do (namely support elements like selects, checkboxes, radios etc) but that shouldn't be too difficult.

Main reason for building it is I absolutely love this library and would love to use it for form validation, as it's syntax is very expressive and easy to use (also adds the possibility of simply sharing your Laravel validation rules from server to client pretty easily). Bootstrap offers a very nice way to show error messages and is generally what I use for most of my front-end projects.

Dominar is extremely expressive and easily configurable (and fast!) straight out of the box. You don't have to edit your markup at all to get it working (all that's needed is your element under validation to be wrapped inside a `.form-group`).

Oh, and it's only 3.5KB gzipped (with validator.js). There isn't another validator out there that is that small with so many features.

It is in the early stages but I would much appreciate if you could share your thoughts on it (coding style, usage of validator.js, etc). Once it becomes more stable I would be very grateful if you would consider linking to it from the validator.js readme. :smile:

**Comment by iamdtang** [comment]
That's awesome! Definitely super useful. I'll have to give it a try on a few things. Thanks for sharing! I starred it =)

**Comment by garygreen** [comment]
Thanks David! I would be forever grateful if you could take a look at the code and help me out with getting tests running in node. It's reliant on jQuery (including $.Deferred), maybe I could refactor some things to make it easier to test? Tried getting jsdom up and running but failed miserably so just got browser tests going atm.

**Comment by iamdtang** [comment]
You might want to check out a test runner that uses PhantomJS. I use Karma for a lot of projects and you can swap out the browser it uses.
