### ISSUE TITLE
Bad publish, I think? There is a merge conflict in the dist

### ISSUE THREAD

**Issue by robclancy** [mikeerickson/validatorjs#382]
I deleted node_modules and installed again and still getting this. Also cleared caches and installed. 
Pretty sure you published a merge conflict (the conflict is on npm only, not on here).

```js
ERROR in ./node_modules/validatorjs/dist/validator.js
Module build failed (from ./node_modules/ember-auto-import/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/robbo/Code/postedin/app/node_modules/validatorjs/dist/validator.js: Unexpected token (1:0)

> 1 | <<<<<<< HEAD
    | ^
  2 | /*! validatorjs - 2019-12-24 */
  3 | =======
  4 | /*! validatorjs - v3.17.0 -  - 2020-08-18 */

```

**Comment by robclancy** [comment]
Went down to 3.19.0 and same issue. Working again on 3.18.x.

**Comment by mikeerickson** [comment]
Hey Rob

This is quite curious?  I  have done clean installs locally and all is working as expected.  How are you including with your project?  

Using the typically require, all works fine?

**Comment by robclancy** [comment]
I went into a new directory, did `yarn cache clean; yarn add validatorjs` and then did `vim node_modules/validatorjs/dist/validator.js` and see the code pasted above.

**Comment by mikeerickson** [comment]
Give me a moment here and I will try again using yarn. I am using npm.

**Comment by robclancy** [comment]
I just did the same process with npm, same thing.

**Comment by mikeerickson** [comment]
@robclancy OK, I have been able to track down and clear the issue.  Quite a bizarre issue, but all is good now.
If you could please give it a quick check, I would appreciate it.

**Comment by robclancy** [comment]
Yep all is good now, thanks.
