### ISSUE TITLE
Array validation rule

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#39]
Would be nice :)

**Comment by iamdtang** [comment]
Do you mean check if a certain value is an array? How do you think `arguments` should be treated?

**Comment by garygreen** [comment]
I was going with simply:

``` javascript
'array': function(val) {
    return typeof val === 'array';
}
```

**Comment by iamdtang** [comment]
I think an array validation would be useful. Using `typeof` wont work though because `typeof []` returns 'object'. You could do a simple `val instanceof Array`.
