### ISSUE TITLE
Only allow attributes in model

### ISSUE THREAD

**Issue by zammitjames** [mikeerickson/validatorjs#392]
How would you go about disallowing additional attributes in the payload that are not in the validator rules, please? 

Thanks!

**Comment by mikeerickson** [comment]
While `validatorjs` does not have internal support for this functionality, you can accomplish what you want with a bit of code after checking initial validation.

```js

const Validator = require("validatorjs")

// data whicn includes attribute not in rule
let data = {
    test: "",
    name: "mike",
}

let rules = {
    test: "required",
}

let validation = new Validator(data, rules)

// post process after initial validation executed
for (const [key, value] of Object.entries(data)) {
    if (!Object.keys(rules).includes(key)) {
        validation.errorCount++
        validation.errors.errors = { ...validation.errors.errors, ...{ [key]: [`The ${key} field is not allowed.`] } }
    }
}

let pass = validation.passes() // true
if (!pass) {
    console.log("\nValidation Errors:")
    console.log(validation.errors.errors)
} else {
    console.log("Validation Passes")
}


```

**Comment by zammitjames** [comment]
Thank you!

> While `validatorjs` does not have internal support for this functionality, you can accomplish what you want with a bit of code after checking initial validation.
> 
> ```js
> const Validator = require("validatorjs")
> 
> // data whicn includes attribute not in rule
> let data = {
>     test: "",
>     name: "mike",
> }
> 
> let rules = {
>     test: "required",
> }
> 
> let validation = new Validator(data, rules)
> 
> // post process after initial validation executed
> for (const [key, value] of Object.entries(data)) {
>     if (!Object.keys(rules).includes(key)) {
>         validation.errorCount++
>         validation.errors.errors = { ...validation.errors.errors, ...{ [key]: [`The ${key} field is not allowed.`] } }
>     }
> }
> 
> let pass = validation.passes() // true
> if (!pass) {
>     console.log("\nValidation Errors:")
>     console.log(validation.errors.errors)
> } else {
>     console.log("Validation Passes")
> }
> ```

Thank you!

**Comment by mikeerickson** [comment]
No problem 🤓
