### ISSUE TITLE
Override default messages

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#41]
Although you can customise the error messages on a per-field basis, it can be quite tedious if you want to always have a different message.

Would be cool to be able to do something like the below (of course still having ability to override with `customMessages`).

``` javascript
Validator.setMessages({
   required: 'This field is required'
});
```

**Comment by mikeerickson** [comment]
+1

**Comment by garygreen** [comment]
PR #42 fixes this
