### ISSUE TITLE
Don't validate as soon as instantiated

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#44]
At the moment validation is run as soon as the instance is created. This makes it diffiuclt to act on the validation object and change defaults, etc before you actually go to validate. I was kind of suprised by this behavior actually, as I assumed it would validate only once you did `passes` or `fails`

Maybe this can be changed? That way you can implement something like the below (which is my idea for PR #40):

``` javascript
var validator = new Validator({ 'users[0][full_name]': ''}, { 'users[0][full_name]': 'required' });
validator.setCustomAttributes({ 'users[0][full_name]': 'Full Name' });
validator.passes();
```

**Comment by iamdtang** [comment]
ya that sounds like a good idea!
