### ISSUE TITLE
Use webpack / browserify

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#45]
Any thoughts on this? It might simplify the test setup and building.

**Comment by iamdtang** [comment]
definitely agree it could clean up the build stuff. that is pretty messy right now. maybe we should use es6 modules instead since everything is heading that way. what do you think?

**Comment by garygreen** [comment]
To be honest quite honest I've never actually used webpack or got much into es6, but hear generally good things. I've used browserify though which is very straightforward and would be a breeze for us to easily support browser and node with minimal filesize bloat and easy testing.

Not sure using es6 just for it's module loading is worth it at this point, as you would still need browserify or webpack ontop of something like babel. Might as well just use browserify and that's it ?

**Comment by iamdtang** [comment]
good point. ok let's go with browserify. i haven't used webpack either.

**Comment by garygreen** [comment]
PR #50
