### ISSUE TITLE
Add common required conditional rules

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#57]
- required_if
- required_with
- required_without

**Comment by vlascik** [comment]
There are several more validations that are missing for Laravel 5.1 parity (http://laravel.com/docs/5.1/validation#available-validation-rules):
- After (Date)
- Before (Date)
- Boolean
- Date
- Date Format
- Digits Between
- IP Address
- JSON
- Required If
- Required Unless
- Required With
- Required With All
- Required Without
- Required Without All
- String
- Timezone

Not sure if any of these would make sense, probably not though?:
- Active URL
- Exists (Database)
- Image (File)
- MIME Types (File)
- Unique (Database)

**Comment by iamdtang** [comment]
Ya I think some of those other ones might be better off as an extension. What do you think @garygreen ?
