### ISSUE TITLE
Support arrays with "in" rule

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#59]
At the moment the `in` rule forces the value to a string. I would expect it to rule true for the below.

``` javascript
var validator = new Validator({ fruits: ['apple', 'strawberry'], { fruits: 'array|in:apple,strawberry' });
validator.passes(); // Should be true.
```

Laravel [supports this](https://github.com/illuminate/validation/blob/master/Validator.php#L981) as well (assuming there is also an `array` rule for the attribute)

**Comment by iamdtang** [comment]
@garygreen Should this be interpreted as, every element in the array value must exist in the list in the validation rule? Or is it, every value in validation rule must be present in the array value (so other things can be present)?

**Comment by garygreen** [comment]
It should operate in the same way as it would with a string and make sure all the values are "in" the array.

``` javascript
var validator = new Validator({ fruits: ['apple', 'strawberry'], { fruits: 'array|in:apple,strawberry,kiwi' });
validator.passes(); // true

var validator = new Validator({ fruits: ['strawberry'], { fruits: 'array|in:apple,strawberry' });
validator.passes(); // true

var validator = new Validator({ fruits: ['strawberry', 'kiwi'], { fruits: 'array|in:apple,strawberry' });
validator.passes(); // false
```
