### ISSUE TITLE
Add stopOnError

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#63]
As soon as first error occurred, stop testing other other validation rules.

**Comment by garygreen** [comment]
Added in e7b3d77ce2a7955b913fa28c0dd3f71223a1a862

Just need to add support for stopOnError only certain fields for asynchronous validation.

**Comment by iamdtang** [comment]
cool!

**Comment by garygreen** [comment]
Funny, Laravel has just added this....after a long time and many requests. They have named it `bail` and put it in the actual rules. Probably a good idea to change it into that style before next release.
