### ISSUE TITLE
Requiring unknown module "./lang/en"

### ISSUE THREAD

**Issue by tristangodfrey** [mikeerickson/validatorjs#65]
I'm trying to use this package in react-native, but unfortunately requiring the module results in the following error:

`
Requiring unknown module "./lang/en". If you are sure the module is there, try restarting the packager.
`

Is this something specific to the fact that I'm using react-native, or am I making a rookie mistake here? Any input would be appreciated.

**Comment by garygreen** [comment]
I know very little about react but based on that error it looks like you should be using the dist build and not one direct from node_modules. Hard to say without seeing how you installed and trying to use it

**Comment by tristangodfrey** [comment]
Thanks for your reply @garygreen 

I installed the package via npm, and in my code I'm just doing this:

```
var Validator = require('validatorjs');
```

What do you mean by using the dist build? I think what's going wrong is that the module in my case is looking for `./lang/en` inside the dist build. This makes sense because that directory only contains `es.js` and `ru.js`, and no English language file.

**Comment by tristangodfrey** [comment]
Alright so I just tried using the dist build, like so:

```
var Validator = require("validatorjs/dist/validator");
```

This lead to the following error:

```
Unable to resolve module ./messages from /node_modules/validatorjs/dist/validator.js: Invalid directory /node_modules/validatorjs/dist/messages
```

Does this tell us anything that might solve the problem?

Also something worth noting is that react-native uses webpack for packaging, not sure wether this has anything to do with the issue though.

**Comment by garygreen** [comment]
Well it should load in the en file [with this](https://github.com/skaterdav85/validatorjs/blob/master/src/lang.js#L3) it works in browserify and node...so I can only say it's probably something different about webpack. I haven't used webpack at all, not really a fan but if you can figure out why it's not working (and if possible send a PR) I would be very greatful ! :)

**Comment by tristangodfrey** [comment]
I guess that must be it then. I've never seen a module requirement without it being loaded into a variable though, (eg. `require('./lang/en');`) could you explain how this works and why the choice was made to do it this way? Would be happy to help find a solution for this.

**Comment by garygreen** [comment]
Can you try loading it into a variable and see if that fixes?

**Comment by tristangodfrey** [comment]
After a bit of debugging I've pinned it down to the following line in `lang.js` : (line 45)

```
var rawMessages = require('./lang/' + lang);
```

Did some testing and realised that the react-native packager doesn't process requires that include variables properly for some reason. I'm pretty sure webpack supports this, so I'll open an issue on the react native packager repo and see if they can offer any clues. Thanks for your input & feedback @garygreen

**Comment by compojoom** [comment]
A year later I ran into the same issue. The current stand is that the react native packager still doesn't support dynamic require. So if you have the same issue you'll have to change 

`var rawMessages = require('./lang/en');`

if you need support for all the languages, the nyou'll have to define each language and based on the value require it. Something like this

var langs = {
en : '.langs/en',
de : '.langs/de'
}

Stupid, but that's the way it works...

**Comment by danieloprado** [comment]
A workaround for this error:

```js
import validator from 'validatorjs';
import lang from 'validatorjs/src/lang';
lang._set('en', {});
```

**Comment by atomicleopard** [comment]
The fix for @danieloprado didn't quite work for me - I adapted it to this, which I include in my root component (i.e. this is a global change). 

```
import lang from 'validatorjs/src/lang';
import en from 'validatorjs/src/lang/en';
lang._set('en', en);
```
