### ISSUE TITLE
Error message is ignored when passed to the register method

### ISSUE THREAD

**Issue by ssylvia** [mikeerickson/validatorjs#68]
Documentation show:
### Registering Custom Validation Rules

``` js
Validator.register(name, callbackFn, errorMessage);
```

**name** {String} - The name of the rule.

**callbackFn** {Function} - Returns a boolean to represent a successful or failed validation.

**errorMessage** {String} - An optional string where you can specify a custom error message. _:attribute_ inside errorMessage will be replaced with the attribute name.

``` js
Validator.register('telephone', function(value, requirement, attribute) { // requirement parameter defaults to null
    return val.match(/^\d{3}-\d{3}-\d{4}$/);
}, 'The :attribute phone number is not in the format XXX-XXX-XXXX.');
```

**Comment by iamdtang** [comment]
It should work. The unit test for it passes:

``` js
var validator = new Validator(
  { phone: '1234567890' }, 
  { phone: 'telephone' }, 
  { telephone: 'Wrong number.' }
);

expect(validator.fails()).to.be.true;
expect(validator.errors.get('phone').length).to.equal(1);
expect(validator.errors.first('phone')).to.equal('Wrong number.');
```

Are you using it like the above?
