### ISSUE TITLE
required_if

### ISSUE THREAD

**Issue by chanlito** [mikeerickson/validatorjs#74]
can someone tell me how the required_if works?? i can't find the example on the doc. thanks in advance.

**Comment by iamdtang** [comment]
See examples here: https://github.com/skaterdav85/validatorjs/blob/master/spec/required_if.js

**Comment by chanlito** [comment]
Thanks again

**Comment by intpp** [comment]
How I can make a field required when an other field undefined(empty)?

**Comment by iamdtang** [comment]
I just added this rule to the docs
