### ISSUE TITLE
How to ignore case sensitive for same rule 

### ISSUE THREAD

**Issue by patelnarendrab** [mikeerickson/validatorjs#80]
Hi,

How ignore case sensitive for same rule. Example:-

Rules:
email: 'required|email',
emailConfirm: 'required|same:email',

Inputs:
email: foo@bar.com
emailConfirm: Foo@Bar.com

Any feedback would be appreciated. Thank you.

**Comment by iamdtang** [comment]
Currently it doesn't support this. You'd have to write a custom rule instead.
