### ISSUE TITLE
accepted should allow boolean true too

### ISSUE THREAD

**Issue by davidspiess** [mikeerickson/validatorjs#81]
In redux-form a value of a checkbox is stored as boolean `true` or `false`. IMO it would make sense to allow `true` not only as string representation in the accepted rule.

**Comment by iamdtang** [comment]
I agree. Would you like to make a PR? If not, I can get to it this weekend.

**Comment by davidspiess** [comment]
It shouldn't be that difficult. I'll give it a try :+1:
