### ISSUE TITLE
Replace several the same placeholders

### ISSUE THREAD

**Issue by valeryq** [mikeerickson/validatorjs#86]
Hi again.

A little proposal. When I define placeholder such as: `It should have :min character or more. Please enter greater then :min characters.`, then replaced only first placeholder. I recommend you replace placeholder such as: 

``` javascript
message = message.replace(new RegExp(':' + attribute, 'g'), data[attribute]);
```

Thank you!

**Comment by iamdtang** [comment]
Agree. Would you like to do this and send a PR? If not, I can get to it later.
