### ISSUE TITLE
"between" rule is not numeric

### ISSUE THREAD

**Issue by marcotisi** [mikeerickson/validatorjs#87]
According to [Laravel's Validator](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Validation/Validator.php#L143),
"between" isn't a numeric rule. Treating it as numeric will break pairing with server side code when a user wants to re-use javascript rules server-side.
In my case i have a field marked with rule "between:10,20"; validatorjs only accepts numeric values between 10 and 20 while Laravel's validator accepts any strings with length between 10 and 20 chars.

**Comment by garygreen** [comment]
Yeah this shouldn't be a numeric rule. I think I did it like that as a quick way around `is_numeric` which Laravel checks for first.

**Comment by marcotisi** [comment]
Great! Will wait for a bugfix!

**Comment by iamdtang** [comment]
Based on  the "between" rule messages, it seems that it allows for either numeric or string values. 

https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L24

We could do a `typeof` check before running the rule as a string vs number. What do you guys think?

**Comment by marcotisi** [comment]
I think that between rule already allows numeric or string values because it gets the size of the value using [getSize()](https://github.com/skaterdav85/validatorjs/blob/master/src/rules.js#L278) method.

The problem is that getSize() checks for the presence of numeric rules to try to determine the value type, and since "between" is contained in numericRules array, the size it returns is parsed by parseFloat().

**Comment by iamdtang** [comment]
I'm a little confused. What should the proper behavior be?

**Comment by marcotisi** [comment]
I think that the correct behavior is Laravel's behavior:

**between:**

> The field under validation must have a size between the given min and max. Strings, numerics, and files are evaluated in the same fashion as the size rule.

**size:**

> The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value. For files, size corresponds to the file size in kilobytes.

Validatorjs already acts like that, but having "between" rule contained in numericRules array, force it to suppose that value is always numeric.

**Comment by iamdtang** [comment]
Would you like to add a PR so that between handles both strings and numbers based on the data type of the input?

**Comment by marcotisi** [comment]
Yeah, give me a couple of days and i will send a PR.

**Comment by iamdtang** [comment]
@mtisi Thanks! Released in version 2.0.11.
