### ISSUE TITLE
[PROPOSAL] Setters and getters for input fields, rules and messages.

### ISSUE THREAD

**Issue by valeryq** [mikeerickson/validatorjs#89]
What are you think about getters and setters? Because not always convenient set this exactly when creating new Validator object.
For example:

``` javascript
class Foo {
   render(input) {
       const validator = new Validator(input, { ... }, { ... });
       if (validator.passes()) {
           // Do something
       }
   }
}
```

It's not convenient and bad for performance in my case -- creating new object always when I calls render function in class.
More convenient when I created Validator object once in constructor:

``` javascript
class Foo {
   constructor() {
       this.validator = new Validator(); // But you can set here input, rules, and messages, but if not, then  values will be default.
   }

   render(input) {
       this.validator.setInput(input).setRules({ ... }).setMessages({ ... });
       if (this.validator.passes()) {
           // Do something
       }
   }
}
```

**Comment by iamdtang** [comment]
The main job of the Validator constructor is to parse the rules. If you delegated the rule setting to a setter, I think it would still be the same code running under a different method and I'm not sure this would help your situation. Maybe the Validator could take rules up front and parse those, and have input set later like in your render method. What do you think @garygreen?

**Comment by valeryq** [comment]
There may be function which parse rules and if rules set in constructor - call parse function, and if set in setter - also call parse function. It's more flexible. And you do not create Validator object over and over again.

**Comment by garygreen** [comment]
I'm not sure why initializing the validator multiple times is such a big performance issue. Why are you initializing it and validating data so many times? Maybe you could restrict it in your app?

I do think however that it may be useful to have a `.setInput()` and `.reset()` method of some form, if you want to re-validate new data but with the same set of rules (which will mostly like be the case). But if we did that you could argue why not a `setRules` etc. The validator wasn't really built for re-running with new data / rules, it's more of a one time thing.

Unless there's a good reason to not initialize the validator again, it probably makes sense to keep it as it is. Alternatively we could find ways of improving the speed of initialization, rule passing / caching etc (although this is probably already pretty quick).

**Comment by valeryq** [comment]
Because for creation and deletion of objects needs to waste time, and if such objects creates a lot of it is bad for performance.
In my case not much time, when customer click submit button.
But setter/getter patternt it isn't bad, it is another enrtypoint and a little better for performance.

**Comment by iamdtang** [comment]
Agree with @garygreen. Thanks for the suggestion @valeryq
