### ISSUE TITLE
How to bind event to validator?

### ISSUE THREAD

**Issue by hansspiess** [mikeerickson/validatorjs#91]
eventually i did not get it right but i would like to use validator.js like so: https://jsfiddle.net/rydfz6tk/
seems like the lib does not bind to its data sources so i will have to init Validator on every keyup again to make it work this way?

**Comment by iamdtang** [comment]
Correct, the data isn't bound so you will have to new up Validator on each key stroke. Let us know if you face any performance issues with this. We've talked about doing something where the rules are parsed only once when the Validator instance is created and being able to set data on the same instance after the fact.
