### ISSUE TITLE
v2.1.0 should have been a major version update

### ISSUE THREAD

**Issue by ghost** [mikeerickson/validatorjs#94]
While using version 2.0.11, I had implemented custom nested validation. NPM by default uses version ^2.0.5
which allowed an automatic update to 2.1.0
The nested validation implementation in 2.1.0 differs slightly to my custom validation which broke things after the update. I have pinned to v2.0.11 for now, but this really should have been a major update as per semver

**Comment by iamdtang** [comment]
ah, sorry! I think we didn't account for custom validation rules. I try my best to follow semver. We'll be more careful next time. I'm not sure what the best course of action is at this point. I could revert the PR and publish as 2.1.1, and then add back the changes and publish as 3.0.0. What do you think?

**Comment by ghost** [comment]
Sounds good, the default NPM mechanism should do the right thing

**Comment by iamdtang** [comment]
Done. Let me know if you have any more issues.
