### ISSUE TITLE
Add option to un-flat the error object

### ISSUE THREAD

**Issue by renarsvilnis** [mikeerickson/validatorjs#97]
Feature request:

Add option to allow to return an un-flat error object by adding an options argument for `Validator`.

``` javascript
/**
 * Default options
 * {
 *   flat: Boolean (Default: true)
 * }
 */
const validation = new Validator(data, rules, {flat: false});
const errors = validation.errors.all();
// > {foo: {bar: 1}}

const validation = new Validator(data, rules);
const errors = validation.errors.all();
// > {'foo.bar': 1}
```

Personally I would find this option useful when using with [`redux-form`](http://redux-form.com/5.2.5/#/examples/synchronous-validation?_k=wmbpbi) where the validation function must return an nested object structure as received.

Additionally the `options` argument could be extended with more features e.g. instance only rules (proposed #98 )

Could be easily added using [`flat.unflatten`](https://github.com/hughsk/flat), rather then implementing your own `unflatten` method.

I can implement the changes if you agree with my proposal.

**Comment by iamdtang** [comment]
How about we make `options` the 4th argument to ensure backwards compatibility. If `options` needs to be passed, the invocation would look like this:

`const validation = new Validator(data, rules, {}, { flat: false });`

**Comment by 5id** [comment]
+1 for this, similar desire to use it with redux-form

**Comment by andrefox333** [comment]
+1 for redux-form!

**Comment by MikeSuiter** [comment]
+1 for redux-form nested errors support. 
 
This library will do the trick but having one less dependency would be nice.

`unflatten(validator.errors.all())`

https://github.com/hughsk/flat

**Comment by garygreen** [comment]
This sounds like something that should live in userland. There's various libraries available to mutate/expand dot format objects, I'm not sure this should be in core functionality.
